function cons_2nd = defineSecondStageConstraints(var_2st, var_u, var_1st)
%DEFINESECONDSTAGECONSTRAINTS Define second-stage constraints
%
%   This function is refactored from examples/original_code/model_grid_2st.m,
%   model_heatingwork_2st.m, model_building_2st.m, model_coupling_1st.m
%   with global variables removed.
%
%   NOTE: This is a simplified version. The original code contains very complex
%   constraint definitions. Users should extract constraints from the original
%   code files and adapt them here, converting uncertainty parameters from
%   numerical values to variable expressions.
%
%   Inputs:
%       data - Data structure
%       var - Variable structure containing base and primal (second-stage) variables
%       var_u - Uncertainty variables structure
%
%   Outputs:
%       cons_2nd - YALMIP constraint object for second-stage constraints
global data
cons_2nd = [];

%%%%%%%%%%%%%--------------------------------------------grid-------------------------------%%%
%%
[loc_gridprice_buy, loc_gridprice_sell] = deal(1,2);             % grid price
[loc_bus, loc_bustype, loc_volmax, loc_volmin] = deal(1,2,12,13);    % bus
[loc_fbus, loc_tbus, loc_r, loc_x] = deal(2,3,4,5);              % branch
[loc_devicebus, loc_devicetype, loc_pmax, loc_pmin, ...
    loc_es_cap, loc_es_pchr, loc_es_pdis, ...
    loc_es_etachr, loc_es_etadis, loc_es_loss, ...
    loc_es_capmax, loc_es_capmin, loc_es_capinitial, ...
    loc_gt_eta, loc_gt_loss, loc_gt_etahr, loc_eb_eta] = ...
    deal(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,14);   % device
[loc_profilesbus, loc_profilestype] = deal(1,2);       % profiles
[loc_c2, loc_c1, loc_c0, loc_penalty, loc_om] = deal(5,6,7,8,9); % cost

%%
num_period = data.period;
num_bus = size(data.grid.bus,1);
num_branch = size(data.grid.branch,1);
baseKV = data.grid.bus(1,10);
set_res = find(data.device.param(:,loc_devicetype) == 1);
set_es = find(data.device.param(:,loc_devicetype) == 2);
set_gt = find(data.device.param(:,loc_devicetype) == 3);
set_eb = find(data.device.param(:,loc_devicetype) == 4);
set_tst = find(data.device.param(:,loc_devicetype) == 5);
set_load = find(data.profiles.bus(:,loc_profilestype) == 1);
set_res_power = find(data.profiles.bus(:,loc_profilestype) == 2);

busset_res = data.device.param(set_res,loc_devicebus);
busset_es = data.device.param(set_es,loc_devicebus);
busset_gt = data.device.param(set_gt,loc_devicebus);
busset_eb = data.device.param(set_eb,loc_devicebus);
busset_tst = data.device.param(set_tst,loc_devicebus);
busset_load = data.profiles.bus(set_load,loc_profilesbus);
busset_res_power = data.profiles.bus(set_res_power,loc_profilesbus);
complete_busset = [1:num_bus];





%% ------------------------ Dist Flow -----------------------------
    for i = 1:num_bus
        Upline = find(data.grid.branch(:,loc_tbus) == i);
        Downline = find(data.grid.branch(:,loc_fbus) == i);
        % % bus power
        % % PCC bus
        if isempty(Upline) && ~isempty(Downline)
            cons_2nd = cons_2nd + ( ...
                (var_2st.bus.p_bus(:,i) == ...
                var_2st.pcc.p(:,1) - ...
                var_2st.pcc.p(:,2) + ...
                var_2st.bus.p_res(:,i) + ...
                var_2st.bus.p_es(:,i) + ...
                var_2st.bus.p_gt(:,i) - ...
                var_2st.bus.p_eb(:,i) - ...
                var_2st.bus.p_load(:,i)) : ...
                'p of bus PCC'); %#ok<*BDSCA>
            cons_2nd = cons_2nd + ( ...
                (var_2st.bus.q_bus(:,i) == ...
                var_2st.pcc.q(:,1) - ...
                var_2st.pcc.q(:,2) - ...
                var_2st.bus.p_load(:,i)) :  ...
                'q of bus PCC');
            % % intersaction node & load node
        else
            cons_2nd = cons_2nd + ( ...
                (var_2st.bus.p_bus(:,i) == ...
                var_2st.bus.p_res(:,i) + ...
                var_2st.bus.p_es(:,i) + ...
                var_2st.bus.p_gt(:,i) - ...
                var_2st.bus.p_eb(:,i) - ...
                var_2st.bus.p_load(:,i)) : ...
                'p of bus PCC');
            cons_2nd = cons_2nd + ( ...
                (var_2st.bus.q_bus(:,i) == ...
                -var_2st.bus.q_load(:,i)) : ...
                'q of bus PCC');
        end
        
        % % bus balance
        cons_2nd = cons_2nd + ( ...
            (var_2st.bus.p_bus(:,i) + ...
            sum(var_2st.branch.p(:,Upline), 2) == ...
            sum(var_2st.branch.p(:,Downline), 2)) : ...
            'p balance of bus');
        cons_2nd = cons_2nd + ( ...
            (var_2st.bus.q_bus(:,i) + ...
            sum(var_2st.branch.q(:,Upline), 2) == ...
            sum(var_2st.branch.q(:,Downline), 2)) : ...
            'q balance of bus');
    end
    
    % % Equation of vol
    for i = 1:num_bus
        Upline = find(data.grid.branch(:,loc_tbus) == i);
        Upbus = data.grid.branch(Upline, loc_fbus);
        if data.grid.bus(i,loc_bustype) == 3  % bus of PCC
            cons_2nd = cons_2nd + ( ...
                (var_2st.bus.vol_bus(:,i) == 1) : ...
                'Vol of PCC');
        else
            cons_2nd = cons_2nd + ( ...
                (var_2st.bus.vol_bus(:,i) == ...
                var_2st.bus.vol_bus(:,Upbus) - ...
                1/baseKV^2*1e-3* ...
                (data.grid.branch(Upbus, loc_r)* ...
                var_2st.branch.p(:,Upline) + ...
                data.grid.branch(Upbus, loc_x)* ...
                var_2st.branch.q(:,Upline))) : ...
                'Vol of bus');
        end
        
        cons_2nd = cons_2nd + ( ...
            (data.grid.bus(i,loc_volmin) <= ...
            var_2st.bus.vol_bus(:,i) <= ...
            data.grid.bus(i,loc_volmax)) : ...
            'limit of vol_bus');
    end
        

%% -------------------- Equations of bus & device ------------------
    if ~isempty(setdiff(complete_busset,busset_res))
        cons_2nd = cons_2nd + ( ...
            (var_2st.bus.p_res ...
            (:,setdiff(complete_busset,busset_res)) == 0) : ...
            '');
    end
    if ~isempty(setdiff(complete_busset,busset_es))
        cons_2nd = cons_2nd + ( ...
            (var_2st.bus.p_es ...
            (:,setdiff(complete_busset,busset_es)) == 0) : ...
            '');
    end
    if ~isempty(setdiff(complete_busset,busset_gt))
        cons_2nd = cons_2nd + ( ...
            (var_2st.bus.p_gt ...
            (:,setdiff(complete_busset,busset_gt)) == 0) : ...
            '');
    end
    if ~isempty(setdiff(complete_busset,busset_eb))
        cons_2nd = cons_2nd + ( ...
            (var_2st.bus.p_eb ...
            (:,setdiff(complete_busset,busset_eb)) == 0) : ...
            '');
    end
    % % Bus with device
    if ~isempty(set_res)
        cons_2nd = cons_2nd + ( ...
            (var_2st.bus.p_res(:,busset_res) == ...
            var_2st.res.p) : ...
            '');
    end
    if ~isempty(set_es)
        cons_2nd = cons_2nd + ( ...
            (var_2st.bus.p_es(:,busset_es) == ...
            var_2st.es.p_dis - var_2st.es.p_chr) : ...
            '');
    end
    if ~isempty(set_gt)
        cons_2nd = cons_2nd + ( ...
            (var_2st.bus.p_gt(:,busset_gt) == ...
            var_2st.gt.p) : ...
            '');
    end
    if ~isempty(set_eb)
        cons_2nd = cons_2nd + ( ...
            (var_2st.bus.p_eb(:,busset_eb) == ...
            var_2st.eb.p) : ...
            '');
    end

%% -------------------------- PCC ----------------------------------
    cons_2nd = cons_2nd + ( ...
        (0 <= var_2st.pcc.p <= ...
        data.grid.p_pcc) : '');
    cons_2nd = cons_2nd + ( ...
        (0 <= var_2st.pcc.q <= ...
        data.grid.p_pcc) : '');

%% -------------------------- Device -------------------------------
    % % res  默认功率数据顺序与设备数据顺序相一致
    % % res
    if ~isempty(set_res)
        cons_2nd = cons_2nd + ( ...
            (0 <= var_2st.res.p <= ...
            var_2st.res.p_fore) : ...
            '');
    end
    % % es
    if ~isempty(set_es)
        cons_2nd = cons_2nd + ( ...
            (var_2st.es.p_chr == var_1st.es.p_chr) : ...
            '');
        cons_2nd = cons_2nd + ( ...
            (var_2st.es.p_dis == var_1st.es.p_dis) : ...
            '');     
    end
    % % tst
    if ~isempty(set_tst)
        cons_2nd = cons_2nd + ( ...
            (var_2st.tst.h_chr == var_1st.tst.h_chr) : ...
            '');
        cons_2nd = cons_2nd + ( ...
            (var_2st.tst.h_dis == var_1st.tst.h_dis) : ...
            '');     
    end
    
    % % gt
    if ~isempty(set_gt)
        cons_2nd = cons_2nd + ( ...
            (var_1st.gt.state.* ...
            (ones(num_period,1)*data.device.param(set_gt, loc_pmin)') <= ...
            var_2st.gt.p <= ...
            var_1st.gt.state.* ...
            (ones(num_period,1)*data.device.param(set_gt, loc_pmax)') ...
            ) : 'limit on p of gt');
        cons_2nd = cons_2nd + ( ...
            (var_2st.gt.h == ...
            ones(num_period,1)* ...
            data.device.param(set_gt, loc_gt_etahr)'.* ...
            (1./data.device.param(set_gt, loc_gt_eta)' - 1 - ...
            data.device.param(set_gt, loc_gt_loss)').* ...
            var_2st.gt.p ...
            ) : 'h-p of gt');
        cons_2nd = cons_2nd + ( ...
            (var_2st.gt.gas == ...
            (ones(num_period, 1)*data.device.param(set_gt, loc_gt_eta)') .* ...
            var_2st.gt.p ...
            ) : 'gas of gt');
    end
    
    % % eb
    if ~isempty(set_eb)
        cons_2nd = cons_2nd + ( ...
            (0 <= var_2st.eb.p <= ...
            ones(num_period,1)*data.device.param(set_eb, loc_pmax)') : ...
            'limit on p of eb');
        cons_2nd = cons_2nd + ( ...
            (var_2st.eb.h == ...
            (ones(num_period,1)*data.device.param(set_eb, loc_eb_eta)').* ...
            (var_2st.eb.p)) : ...
            'h of eb');
    end

%% uncertainty
    % % res
    cons_2nd = cons_2nd + ( ...
        (var_2st.res.p_fore(:,:) == ...
        data.profiles.data(set_res_power, :)' .* ( 1 + ...
        data.uncertainty.Deviation.p_res * ...
        var_u.p_res_pos - ...
        data.uncertainty.Deviation.p_res * ...
        var_u.p_res_neg)) : ...
        '');
    % % load
    if ~isempty(setdiff(complete_busset, busset_load))
        cons_2nd = cons_2nd + ( ...
            (var_2st.bus.p_load(:,setdiff(complete_busset, busset_load)) ==  ...
            0) : 'load of bus');
    end
    if ~isempty(set_load)
        cons_2nd = cons_2nd + ( ...
            (var_2st.bus.p_load(:,busset_load) == ...
            data.profiles.data(set_load,:)' .* ( 1 + ...
            data.uncertainty.Deviation.p_load * ...
            var_u.p_load_pos - ...
            data.uncertainty.Deviation.p_load * ...
            var_u.p_load_neg)) : 'p load of bus');
        
        cons_2nd = cons_2nd + ( ...
            (var_2st.bus.q_load(:,busset_load) == ...
            0) : 'q load of bus');
    end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-------------------------heating----------------------------%%%%%%%%%%%%%%%%%%
[loc_fnode, loc_tnode, loc_length, loc_diameter, loc_rough, ...
    loc_conductivity, loc_massflow] = deal(1,2,3,4,5,6,9);    % pipe
[loc_nodeno, loc_nodetype, loc_Tsmin, loc_Tsmax, loc_Trmin, loc_Trmax] = ...
    deal(1,2,3,4,5,6);                                        % node
[loc_initial_Tau_s, loc_initial_Tau_r, loc_initial_Tau_amb] = ...
    deal(1,2,3);
% % - Data
rho_w = 1;     % t/m^3;
c_w = 4200;  % MJ/(t*¡æ)
pi = 3.1416;
num_initialtime = data.num_initialtime;
num_period_heat = data.period*data.interval.electricity/data.interval.heat;
num_start = num_initialtime+1;
num_end = num_initialtime+num_period_heat;
data_pipe = data.heatingnetwork.pipe;
data_node = data.heatingnetwork.node;
data_initial = data.heatingnetwork.initial;
num_pipe = size(data_pipe,1);
num_node = size(data_node,1);
num_source = sum(data_node(:,loc_nodetype) == 0);
num_load = sum(data_node(:,loc_nodetype) == 2);
data_Tau_amb = ones(2*num_initialtime+num_period_heat,1)*data_initial(loc_initial_Tau_amb);
data.param_Tau_amb = [data_Tau_amb(end-num_initialtime:end,1); ...
    data_Tau_amb; data_Tau_amb(1:num_initialtime,1)];
%% Calculate basic parameters
Area = data_pipe(:,loc_diameter).^2*pi/4;
gamma = ceil(rho_w*Area.*data_pipe(:,loc_length)./...
    data_pipe(:,loc_massflow)./data.interval.heat) - 1;
R = (gamma + 1).*data_pipe(:,loc_massflow)*data.interval.heat;
kappa = (R - rho_w*Area.*data_pipe(:,loc_length))./...
    data_pipe(:,loc_massflow)./data.interval.heat;
beta = exp(-data_pipe(:,loc_conductivity).* ...
    data_pipe(:,loc_length)./(c_w*data_pipe(:,loc_massflow)));
%% Write in params of heating network
data.heatingnetwork.params.Area = Area;
data.heatingnetwork.params.gamma = gamma;
data.heatingnetwork.params.R = R;
data.heatingnetwork.params.kappa = kappa;
data.heatingnetwork.params.beta = beta;

%% Initialize variable
var_2st.heatingnetwork.Tau_pipe_s_in(1:num_initialtime,:) = ...
    data_initial(loc_initial_Tau_s);
var_2st.heatingnetwork.Tau_pipe_r_in(1:num_initialtime,:) = ...
    data_initial(loc_initial_Tau_r);
var_2st.heatingnetwork.Tau_pipe_s_out(1:num_initialtime,:) = ...
    data_initial(loc_initial_Tau_s);
var_2st.heatingnetwork.Tau_pipe_r_out(1:num_initialtime,:) = ...
    data_initial(loc_initial_Tau_r);
var_2st.heatingnetwork.Tau_node_s(1:num_initialtime,:) = ...
    data_initial(loc_initial_Tau_s);
var_2st.heatingnetwork.Tau_node_r(1:num_initialtime,:) = ...
    data_initial(loc_initial_Tau_r);
var_2st.heatingnetwork.h_source(1:num_initialtime,:) = 0;
var_2st.heatingnetwork.h_load(1:num_initialtime,:) = 0;

%% Temperature quasi-dynamic
t = num_start : num_end;
for j = 1:num_pipe
    cons_2nd = cons_2nd + ( ...
        (var_2st.heatingnetwork.Tau_pipe_s_out(t,j) == ...
        (1-beta(j)) * data.param_Tau_amb(t) + ...
        beta(j) * ...
        ((1-kappa(j)) * ...
        var_2st.heatingnetwork.Tau_pipe_s_in(t-gamma(j)-1,j) + ...
        kappa(j) * ...
        var_2st.heatingnetwork.Tau_pipe_s_in(t-gamma(j),j))) : ...
        'heatingsys: supply Tau of pipe ');
    cons_2nd = cons_2nd + ( ...
        (var_2st.heatingnetwork.Tau_pipe_r_out(t,j) == ...
        (1-beta(j)) * data.param_Tau_amb(t) + ...
        beta(j) * ...
        ((1-kappa(j)) * ...
        var_2st.heatingnetwork.Tau_pipe_r_in(t-gamma(j)-1,j) + ...
        kappa(j) * ...
        var_2st.heatingnetwork.Tau_pipe_r_in(t-gamma(j),j))) : ...
        'heatingsys: return Tau of pipe ');
end


%% Nodal balance
t = num_start : num_end;

for i = 1:num_node
    set_pipe_fnode = [];
    set_pipe_tnode = [];
    current_node = data_node(i,loc_nodeno); %% ÓÉ0½Úµãµ¼ÖÂµÄbug
    for j = 1:num_pipe
        if data_pipe(j,loc_fnode) == current_node   % pipeline from this node
            set_pipe_fnode(end+1) = j;
        elseif data_pipe(j,loc_tnode) == current_node % pipeline to this node
            set_pipe_tnode(end+1) = j;
        end
    end
    % --- Source node
    if data_node(i,loc_nodetype) == 0
        if ~isempty(set_pipe_fnode)
            cons_2nd = cons_2nd + ( ...
                (var_2st.heatingnetwork.Tau_pipe_s_in(t,set_pipe_fnode) == ...
                var_2st.heatingnetwork.Tau_node_s(t,i)) : ...
                ['heatingsys: suppley Tau of source node ' num2str(current_node)]);
            cons_2nd = cons_2nd + ( ...
                (var_2st.heatingnetwork.Tau_pipe_r_out(t,set_pipe_fnode) == ...
                var_2st.heatingnetwork.Tau_node_r(t,i)) : ...
                ['heatingsys: return Tau of source node ' num2str(current_node)]);
            cons_2nd = cons_2nd + ( ...
                (var_2st.heatingnetwork.h_source(t,1) == ...
                c_w*data_pipe(set_pipe_fnode,loc_massflow)/3600*...
                (var_2st.heatingnetwork.Tau_node_s(t,i) - ...
                var_2st.heatingnetwork.Tau_node_r(t,i))) : ...
                ['heatingsys: power balance at source node ' num2str(current_node)]);
        end
    end
    % % --- Cross node
    if data_node(i,loc_nodetype) == 1
        % % ---- supply network
        if ~isempty(set_pipe_fnode)
            if isempty(set_pipe_tnode)
                fprintf('\n Error: There is something wrong with the data of Heating Network. (Supply Network: node %d)\n', num2str(current_node));
                return;
            end
            cons_2nd = cons_2nd + ( ...
                (var_2st.heatingnetwork.Tau_pipe_s_in(t,set_pipe_fnode) == ...
                var_2st.heatingnetwork.Tau_node_s(t,i)*ones(1,length(set_pipe_fnode))) : ...
                ['heatingsys: supply Tau of cross node ' num2str(current_node)]);
            cons_2nd = cons_2nd + ( ...
                (var_2st.heatingnetwork.Tau_node_s(t,i)* ...
                sum(data_pipe(set_pipe_fnode,loc_massflow)) == ...
                var_2st.heatingnetwork.Tau_pipe_s_out(t,set_pipe_tnode)* ...
                data_pipe(set_pipe_tnode,loc_massflow)) : ...
                ['heatingsys: power balance at supply cross node ' num2str(current_node)]);
        end
        % % ---- Return network
        if ~isempty(set_pipe_tnode)
            if isempty(set_pipe_fnode)
                fprintf('\n Error: There is something wrong with the data of Heating Network. (Return Network: node %d)\n', current_node);
                return;
            end
            cons_2nd = cons_2nd + ( ...
                (var_2st.heatingnetwork.Tau_pipe_r_in(t,set_pipe_tnode) == ...
                var_2st.heatingnetwork.Tau_node_r(t,i)*ones(1,length(set_pipe_tnode))) : ...
                ['heatingsys: return Tau of cross node ' num2str(current_node)]);
            cons_2nd = cons_2nd + ( ...
                (var_2st.heatingnetwork.Tau_node_r(t,i)* ...
                sum(data_pipe(set_pipe_tnode,loc_massflow)) == ...
                var_2st.heatingnetwork.Tau_pipe_r_out(t,set_pipe_fnode)* ...
                data_pipe(set_pipe_fnode,loc_massflow)) : ...
                ['heatingsys: power balance at return cross node ' num2str(current_node)]);
        end
    end
    % % --- Load node
    if data_node(i,loc_nodetype) == 2
        if ~isempty(set_pipe_tnode)
            cons_2nd = cons_2nd + ( ...
                (var_2st.heatingnetwork.Tau_pipe_s_out(t,set_pipe_tnode) == ...
                var_2st.heatingnetwork.Tau_node_s(t,i)*ones(1,length(set_pipe_tnode))) : ...
                ['heatingsys: supply Tau of load node ' num2str(current_node)]);
            cons_2nd = cons_2nd + ( ...
                (var_2st.heatingnetwork.Tau_pipe_r_in(t,set_pipe_tnode) == ...
                var_2st.heatingnetwork.Tau_node_r(t,i)*ones(1,length(set_pipe_tnode))) : ...
                ['heatingsys: return Tau of load node ' num2str(current_node)]);
            cons_2nd = cons_2nd + ( ...
                (var_2st.heatingnetwork.h_load(t, ...
                sum(data_node(1:i,loc_nodetype) == 2)) == ...
                c_w*data_pipe(set_pipe_tnode,loc_massflow)/3600* ...
                (var_2st.heatingnetwork.Tau_node_s(t,i) - ...
                var_2st.heatingnetwork.Tau_node_r(t,i))) : ...
                ['heatingsys: power balance at load node ' num2str(current_node)]);
        end
    end
end

%% Node temperature limit
cons_2nd = cons_2nd + ( ...
    (var_2st.heatingnetwork.Tau_node_s(:,:) >= ...
    data_node(1,loc_Tsmin)) : '');
cons_2nd = cons_2nd + ( ...
    (var_2st.heatingnetwork.Tau_node_s(:,:) <= ...
    data_node(1,loc_Tsmax)) : '');
cons_2nd = cons_2nd + ( ...
    (var_2st.heatingnetwork.Tau_node_r(:,:) >= ...
    data_node(1,loc_Trmin)) : '');
cons_2nd = cons_2nd + ( ...
    (var_2st.heatingnetwork.Tau_node_r(:,:) <= ...
    data_node(1,loc_Trmax)) : '');

%% Final states constraints: supply temperature
cons_2nd = cons_2nd + ( ...
    (var_2st.heatingnetwork.Tau_node_s(num_end,1) >= ...
    data_initial(loc_initial_Tau_s)) : '');
cons_2nd = cons_2nd + ( ...
    (var_2st.heatingnetwork.Tau_node_r(num_end,1) <= ...
    data_initial(loc_initial_Tau_r)) : '');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%------------------------building------------------------------%%%%%%%%%%%%%%%%%%%%%%%%
%% Params
[loc_buildingno, loc_node, loc_C, loc_R, loc_num] = ...
    deal(1,2,3,4,5);
[loc_Tau_low, loc_Tau_up, loc_Tau_opt] = deal(1,2,3);
num_period_heat = data.period*data.interval.electricity/data.interval.heat;
num_extrmpoint = size(data.buildings.uncertainty.alpha,2);

%% Data
Tau_out = data.profiles.data(data.profiles.bus(:,2)==3,:)';
t = 1:num_period_heat;
data.buildings.Tau_out(t,1) = Tau_out( ...
    fix((t-1)*data.interval.heat)/data.interval.electricity+1,1);
num_building = size(data.buildings.param,1);
ratio = exp(-data.interval.heat./data.buildings.param(:,loc_R)' ...
    ./data.buildings.param(:,loc_C)');

%% Modeling
% % -- Temperature equations
cons_2nd = cons_2nd + ( ...
    (var_2st.building.h_load >= 0) : '');
cons_2nd = cons_2nd + ( ...
    (var_2st.building.Tau_in(1,:) == ...
    ratio * data.buildings.limit(loc_Tau_opt) + ...
    var_2st.building.Tau_act(1,:) + ...
    (1-ratio) .* ...
    (var_2st.building.Tau_out(1,1) + ...
    data.buildings.param(:,loc_R)'./data.buildings.param(:,loc_num)' .* ...
    var_2st.building.h_load(1,:))) : ...
    'Buildings: Tau equation');
cons_2nd = cons_2nd + ( ...
    (var_2st.building.Tau_in(2:end,:) == ...
    ones(num_period_heat-1,1)*ratio .* ...
    var_2st.building.Tau_in(1:end-1,:) + ...
    var_2st.building.Tau_act(2:end,:) + ...
    ones(num_period_heat-1,1) *(1-ratio) .* ...
    (var_2st.building.Tau_out(2:end,1)*ones(1,num_building) + ...
    ones(num_period_heat-1,1) * ...
    (data.buildings.param(:,loc_R)./data.buildings.param(:,loc_num))' .* ...
    var_2st.building.h_load(2:end,:))) : ...
    'Buildings: Tau equation');

% % -- Temperature limit
cons_2nd = cons_2nd + ( ...
    (var_2st.building.Tau_in >= data.buildings.limit(loc_Tau_low)) : ...
    'Buildings: temperature limit');
cons_2nd = cons_2nd + ( ...
    (var_2st.building.Tau_in <= data.buildings.limit(loc_Tau_up)) : ...
    'Buildings: temperature limit');
cons_2nd = cons_2nd + ( ...
    (var_2st.building.Tau_in(end,:) == ...
    data.buildings.limit(loc_Tau_opt)) : ...
    'Buildings: endpoint temperature');

% % -- Average Temperature
cons_2nd = cons_2nd + ( ...
    (ones(num_building, num_period_heat)*var_2st.building.Tau_in == ...
    num_period_heat*data.buildings.limit(loc_Tau_opt)) : ...
    'Buildings: average Tau');

% % Tau_out
cons_2nd = cons_2nd + ( ...
    (var_2st.building.Tau_out == ...
    data.buildings.Tau_out .* ( 1 + ...
    data.uncertainty.Deviation.Tau_out * ...
    var_u.Tau_out_pos - ...
    data.uncertainty.Deviation.Tau_out * ...
    var_u.Tau_out_neg)) : 'Tau_out');
% % Tau_act
cons_2nd = cons_2nd + ( ...
    (var_2st.building.Tau_act == ...
    data.buildings.Tau_act' .* ( 1 + ...
    data.uncertainty.Deviation.Tau_act * ...
    var_u.Tau_act_pos - ...
    data.uncertainty.Deviation.Tau_act * ...
    var_u.Tau_act_neg)) : 'Tau_act');
    
% % extreme points
for j = 1:num_extrmpoint
    cons_2nd = cons_2nd + ( ...
        (var_2st.building.Tau_in_extrm(1,:,j) == ...
        data.buildings.uncertainty.alpha(:,j)' * ...
        data.buildings.limit(loc_Tau_opt) + ...
        data.buildings.uncertainty.beta(:,j)' .* ...
        var_2st.building.h_load(1,:) + ...
        var_2st.building.Tau_act(1,:) + ...
        (1-data.buildings.uncertainty.alpha(:,j))' * ...
        var_2st.building.Tau_out(1,1)) : ...
        'Buildings: Tau equation');
    cons_2nd = cons_2nd + ( ...
        (var_2st.building.Tau_in_extrm(2:end,:,j) == ...
        ones(num_period_heat-1,1)*data.buildings.uncertainty.alpha(:,j)' .* ...
        var_2st.building.Tau_in_extrm(1:end-1,:,j) + ...
        ones(num_period_heat-1,1)*data.buildings.uncertainty.beta(:,j)' .* ...
        var_2st.building.h_load(2:end,:) + ...
        var_2st.building.Tau_act(2:end,:) + ...
        ones(num_period_heat-1,1)*(1-data.buildings.uncertainty.alpha(:,j))' .* ...
        (var_2st.building.Tau_out(2:end,1)*ones(1, num_building))) : ...
        'Buildings: Tau equation');
    
    cons_2nd = cons_2nd + ( ...
        (var_2st.building.Tau_in_extrm(:,:,j) >= data.buildings.limit(loc_Tau_low)) : ...
        'Buildings: temperature limit');
    cons_2nd = cons_2nd + ( ...
        (var_2st.building.Tau_in_extrm(:,:,j) <= data.buildings.limit(loc_Tau_up)) : ...
        'Buildings: temperature limit');
end

%% Tau_in compensate
for j = 1:num_extrmpoint
    % cons_2nd = cons_2nd + ( ...
    %     data.buildings.limit(loc_Tau_low) <= var_2st.building.Tau_in_extrm(:,:,j) ...
    %     <= data.buildings.limit(loc_Tau_up));
    cons_2nd = cons_2nd + ( ...
        (var_2st.building.Tau_in_upperdelta_pos >= 0) : '');
    cons_2nd = cons_2nd + ( ...
        (var_2st.building.Tau_in_upperdelta_neg >= 0) : '');
    cons_2nd = cons_2nd + ( ...
        (var_2st.building.Tau_in_lowerdelta_pos >= 0) : '');
    cons_2nd = cons_2nd + ( ...
        (var_2st.building.Tau_in_lowerdelta_neg >= 0) : '');

    cons_2nd = cons_2nd + ( ...
        (var_2st.building.Tau_in_extrm(:,:,j) - data.buildings.limit(loc_Tau_up) == ...
        var_2st.building.Tau_in_upperdelta_pos(:,:,j) - ...
        var_2st.building.Tau_in_upperdelta_neg(:,:,j)) : ...
        'Buildings: temperature limit');
    cons_2nd = cons_2nd + ( ...
        (data.buildings.limit(loc_Tau_low) - var_2st.building.Tau_in_extrm(:,:,j) == ...
        var_2st.building.Tau_in_lowerdelta_pos(:,:,j) - ...
        var_2st.building.Tau_in_lowerdelta_neg(:,:,j)) : ...
        'Buildings: temperature limit');

end
big_M_Tau_in = 1e4;
for i1 = 1:num_period_heat
    for i2= 1:num_building
        for i3 = 1:num_extrmpoint
            cons_2nd = cons_2nd + ( ...
                (big_M_Tau_in*var_2st.building.Tau_in_upperdelta_pos(i1,i2,i3) + ...
                big_M_Tau_in*var_2st.building.Tau_in_lowerdelta_pos(i1,i2,i3) <= ...
                var_2st.cost.Tau_in_comp <= 1e6) : ...
                '');
        end
    end
end

%%%%%%%%%%%%%%%%%%%%------------------coupling-------------------%%%%%%%%%%%%%%%%%%%%%%
%%
num_start = data.num_initialtime+1;
num_end = data.num_initialtime + ...
    data.period*data.interval.electricity/data.interval.heat;
%% h_souce
cons_2nd = cons_2nd + ( ...
    (var_2st.gt.h + var_2st.eb.h + ...
    sum(var_2st.tst.h_dis,2) - sum(var_2st.tst.h_chr,2) == ...
    var_2st.heatingnetwork.h_source(num_start:num_end,1)) : ...
    'h balance between eps and heating network'); %#ok<*BDSCA>

%% h_load
cons_2nd = cons_2nd + ( ...
    (var_2st.heatingnetwork.h_load(num_start:num_end,:) == ...
    var_2st.building.h_load) : ...
    'h balance between heating network and buildings');

end
