function model_building_1st(varargin)
if find(strcmp(varargin, 'DisplayTime'))
    DisplayTime = varargin{find(strcmp(varargin, 'DisplayTime'))+1};
else
    DisplayTime = 1;
end
if DisplayTime
    fprintf('%-40s\t\t','- Model building');
    t0 = clock;
end
%%
global data var_1st model big_M_Tau_in;
%% Params
[loc_buildingno, loc_node, loc_C, loc_R, loc_num] = ...
    deal(1,2,3,4,5);
[loc_Tau_low, loc_Tau_up, loc_Tau_opt] = deal(1,2,3);
num_period_heat = data.period*data.interval.electricity/data.interval.heat;
num_scenario = length(model.uncertainty_set);
num_extrmpoint = size(data.buildings.uncertainty.alpha,2);
%% Data
Tau_out = data.profiles.data(data.profiles.bus(:,2)==3,:)';
t = 1:num_period_heat;
data.buildings.Tau_out(t,1) = Tau_out( ...
    fix((t-1)*data.interval.heat)/data.interval.electricity+1,1);
num_building = size(data.buildings.param,1);
ratio = exp(-data.interval.heat./data.buildings.param(:,loc_R)' ...
    ./data.buildings.param(:,loc_C)');

%% Modeling
% % -- Temperature equations
for k = 1:num_scenario
    model.main_problem.cons = model.main_problem.cons + ( ...
        (var_1st.recourse(k).building.h_load >= 0) : '');
    model.main_problem.cons = model.main_problem.cons + ( ...
        (var_1st.recourse(k).building.Tau_in(1,:) == ...
        ratio * data.buildings.limit(loc_Tau_opt) + ...
        var_1st.recourse(k).building.Tau_act(1,:) + ...
        (1-ratio) .* ...
        (var_1st.recourse(k).building.Tau_out(1,1) + ...
        data.buildings.param(:,loc_R)'./data.buildings.param(:,loc_num)' .* ...
        var_1st.recourse(k).building.h_load(1,:))) : ...
        'Buildings: Tau equation');
    model.main_problem.cons = model.main_problem.cons + ( ...
        (var_1st.recourse(k).building.Tau_in(2:end,:) == ...
        ones(num_period_heat-1,1)*ratio .* ...
        var_1st.recourse(k).building.Tau_in(1:end-1,:) + ...
        var_1st.recourse(k).building.Tau_act(2:end,:) + ...
        ones(num_period_heat-1,1) *(1-ratio) .* ...
        (var_1st.recourse(k).building.Tau_out(2:end,1)*ones(1,num_building) + ...
        ones(num_period_heat-1,1) * ...
        (data.buildings.param(:,loc_R)./data.buildings.param(:,loc_num))' .* ...
        var_1st.recourse(k).building.h_load(2:end,:))) : ...
        'Buildings: Tau equation');
    
    % % -- Temperature limit
    model.main_problem.cons = model.main_problem.cons + ( ...
        (var_1st.recourse(k).building.Tau_in >= data.buildings.limit(loc_Tau_low)) : ...
        'Buildings: temperature limit');
    model.main_problem.cons = model.main_problem.cons + ( ...
        (var_1st.recourse(k).building.Tau_in <= data.buildings.limit(loc_Tau_up)) : ...
        'Buildings: temperature limit');
    model.main_problem.cons = model.main_problem.cons + ( ...
        (var_1st.recourse(k).building.Tau_in(end,:) == ...
        data.buildings.limit(loc_Tau_opt)) : ...
        'Buildings: endpoint temperature');
    
    % % -- Average Temperature
    model.main_problem.cons = model.main_problem.cons + ( ...
        (ones(num_building, num_period_heat)*var_1st.recourse(k).building.Tau_in == ...
        num_period_heat*data.buildings.limit(loc_Tau_opt)) : ...
        'Buildings: average Tau');
    
    % % Tau_out
    model.main_problem.cons = model.main_problem.cons + ( ...
        (var_1st.recourse(k).building.Tau_out == ...
        data.buildings.Tau_out .* ( 1 + ...
        data.uncertainty.Deviation.Tau_out * ...
        model.uncertainty_set(k).Tau_out_pos - ...
        data.uncertainty.Deviation.Tau_out * ...
        model.uncertainty_set(k).Tau_out_neg)) : 'Tau_out');
    % % Tau_act
    model.main_problem.cons = model.main_problem.cons + ( ...
        (var_1st.recourse(k).building.Tau_act == ...
        data.buildings.Tau_act' .* ( 1 + ...
        data.uncertainty.Deviation.Tau_act * ...
        model.uncertainty_set(k).Tau_act_pos - ...
        data.uncertainty.Deviation.Tau_act * ...
        model.uncertainty_set(k).Tau_act_neg)) : 'Tau_act');
    
    % % extreme points
    for j = 1:num_extrmpoint
        model.main_problem.cons = model.main_problem.cons + ( ...
            (var_1st.recourse(k).building.Tau_in_extrm(1,:,j) == ...
            data.buildings.uncertainty.alpha(:,j)' * ...
            data.buildings.limit(loc_Tau_opt) + ...
            data.buildings.uncertainty.beta(:,j)' .* ...
            var_1st.recourse(k).building.h_load(1,:) + ...
            var_1st.recourse(k).building.Tau_act(1,:) + ...
            (1-data.buildings.uncertainty.alpha(:,j))' * ...
            var_1st.recourse(k).building.Tau_out(1,1)) : ...
            'Buildings: Tau equation');
        model.main_problem.cons = model.main_problem.cons + ( ...
            (var_1st.recourse(k).building.Tau_in_extrm(2:end,:,j) == ...
            ones(num_period_heat-1,1)*data.buildings.uncertainty.alpha(:,j)' .* ...
            var_1st.recourse(k).building.Tau_in_extrm(1:end-1,:,j) + ...
            ones(num_period_heat-1,1)*data.buildings.uncertainty.beta(:,j)' .* ...
            var_1st.recourse(k).building.h_load(2:end,:) + ...
            var_1st.recourse(k).building.Tau_act(2:end,:) + ...
            ones(num_period_heat-1,1)*(1-data.buildings.uncertainty.alpha(:,j))' .* ...
            (var_1st.recourse(k).building.Tau_out(2:end,1)*ones(1, num_building))) : ...
            'Buildings: Tau equation');
        
        model.main_problem.cons = model.main_problem.cons + ( ...
            (var_1st.recourse(k).building.Tau_in_extrm(:,:,j) >= data.buildings.limit(loc_Tau_low)) : ...
            'Buildings: temperature limit');
        model.main_problem.cons = model.main_problem.cons + ( ...
            (var_1st.recourse(k).building.Tau_in_extrm(:,:,j) <= data.buildings.limit(loc_Tau_up)) : ...
            'Buildings: temperature limit');
    end
    
end

%% Tau_in compensate
for k = 1:num_scenario
    for j = 1:num_extrmpoint
        model.main_problem.cons = model.main_problem.cons + ( ...
            (var_1st.recourse(k).building.Tau_in_upperdelta_pos >= 0) : '');
        model.main_problem.cons = model.main_problem.cons + ( ...
            (var_1st.recourse(k).building.Tau_in_upperdelta_neg >= 0) : '');
        model.main_problem.cons = model.main_problem.cons + ( ...
            (var_1st.recourse(k).building.Tau_in_lowerdelta_pos >= 0) : '');
        model.main_problem.cons = model.main_problem.cons + ( ...
            (var_1st.recourse(k).building.Tau_in_lowerdelta_neg >= 0) : '');
        
        model.main_problem.cons = model.main_problem.cons + ( ...
            (var_1st.recourse(k).building.Tau_in_extrm(:,:,j) - data.buildings.limit(loc_Tau_up) == ...
            var_1st.recourse(k).building.Tau_in_upperdelta_pos(:,:,j) - ...
            var_1st.recourse(k).building.Tau_in_upperdelta_neg(:,:,j)) : ...
            'Buildings: temperature limit');
        model.main_problem.cons = model.main_problem.cons + ( ...
            (data.buildings.limit(loc_Tau_low) - var_1st.recourse(k).building.Tau_in_extrm(:,:,j) == ...
            var_1st.recourse(k).building.Tau_in_lowerdelta_pos(:,:,j) - ...
            var_1st.recourse(k).building.Tau_in_lowerdelta_neg(:,:,j)) : ...
            'Buildings: temperature limit');
        
    end
    for i1 = 1:num_period_heat
        for i2= 1:num_building
            for i3 = 1:num_extrmpoint
                model.main_problem.cons = model.main_problem.cons + ( ...
                    (var_1st.recourse(k).cost.Tau_in_comp >= ...
                    big_M_Tau_in*var_1st.recourse(k).building.Tau_in_upperdelta_pos(i1,i2,i3) + ...
                    big_M_Tau_in*var_1st.recourse(k).building.Tau_in_lowerdelta_pos(i1,i2,i3)) : ...
                    '');
            end
        end
    end
end

%%
if DisplayTime
    t1 = clock;
    fprintf('%8.2f%s\n', etime(t1,t0), 's');
end
end