function model_grid_2st(varargin)
if find(strcmp(varargin, 'DisplayTime'))
    DisplayTime = varargin{find(strcmp(varargin, 'DisplayTime'))+1};
else
    DisplayTime = 1;
end
if DisplayTime
    fprintf('%-40s\t\t','- Model grid');
    t0 = clock;
end
%%
global data model var_1st var_2st ;
[loc_gridprice_buy, loc_gridprice_sell] = deal(1,2);             % grid price
[loc_bus, loc_bustype, loc_volmax, loc_volmin] = deal(1,2,12,13);    % bus
[loc_fbus, loc_tbus, loc_r, loc_x] = deal(2,3,4,5);              % branch
[loc_devicebus, loc_devicetype, loc_pmax, loc_pmin, ...
    loc_es_cap, loc_es_pchr, loc_es_pdis, ...
    loc_es_etachr, loc_es_etadis, loc_es_loss, ...
    loc_es_capmax, loc_es_capmin, loc_es_capinitial, ...
    loc_gt_eta, loc_gt_loss, loc_gt_etahr, loc_eb_eta] = ...
    deal(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,14);   % device
[loc_profilesbus, loc_profilestype] = deal(1,2);       % profiles
[loc_c2, loc_c1, loc_c0, loc_penalty, loc_om] = deal(5,6,7,8,9); % cost

%%
num_period = data.period;
num_bus = size(data.grid.bus,1);
num_branch = size(data.grid.branch,1);
baseKV = data.grid.bus(1,10);
set_res = find(data.device.param(:,loc_devicetype) == 1);
set_es = find(data.device.param(:,loc_devicetype) == 2);
set_gt = find(data.device.param(:,loc_devicetype) == 3);
set_eb = find(data.device.param(:,loc_devicetype) == 4);
set_tst = find(data.device.param(:,loc_devicetype) == 5);
set_load = find(data.profiles.bus(:,loc_profilestype) == 1);
set_res_power = find(data.profiles.bus(:,loc_profilestype) == 2);

busset_res = data.device.param(set_res,loc_devicebus);
busset_es = data.device.param(set_es,loc_devicebus);
busset_gt = data.device.param(set_gt,loc_devicebus);
busset_eb = data.device.param(set_eb,loc_devicebus);
busset_tst = data.device.param(set_tst,loc_devicebus);
busset_load = data.profiles.bus(set_load,loc_profilesbus);
busset_res_power = data.profiles.bus(set_res_power,loc_profilesbus);
complete_busset = [1:num_bus];
%% Distflow
model_distflow();
%% Bus-Device balance
model_equBusDevice();
%% PCC
model_pcc();
%% Device
model_device();
%% uncertainty
% % res
model.sub_problem.cons = model.sub_problem.cons + ( ...
    (var_2st.primal.res.p_fore(:,:) == ...
    data.profiles.data(set_res_power, :)' .* ( 1 + ...
    data.uncertainty.Deviation.p_res * ...
    var_2st.primal.uncertainty.p_res_pos - ...
    data.uncertainty.Deviation.p_res * ...
    var_2st.primal.uncertainty.p_res_neg)) : ...
    '');
% % load
if ~isempty(setdiff(complete_busset, busset_load))
    model.sub_problem.cons = model.sub_problem.cons + ( ...
        (var_2st.primal.bus.p_load(:,setdiff(complete_busset, busset_load)) ==  ...
        0) : 'load of bus');
end
if ~isempty(set_load)
    model.sub_problem.cons = model.sub_problem.cons + ( ...
        (var_2st.primal.bus.p_load(:,busset_load) == ...
        data.profiles.data(set_load,:)' .* ( 1 + ...
        data.uncertainty.Deviation.p_load * ...
        var_2st.primal.uncertainty.p_load_pos - ...
        data.uncertainty.Deviation.p_load * ...
        var_2st.primal.uncertainty.p_load_neg)) : 'p load of bus');
    
    model.sub_problem.cons = model.sub_problem.cons + ( ...
        (var_2st.primal.bus.q_load(:,busset_load) == ...
        0) : 'q load of bus');
end
%% Cost
model_cost();

%%
if DisplayTime
    t1 = clock;
    fprintf('%8.2f%s\n', etime(t1,t0), 's');
end

%% ------------------------ Dist Flow ------------------------------
    function model_distflow()
        for i = 1:num_bus
            Upline = find(data.grid.branch(:,loc_tbus) == i);
            Downline = find(data.grid.branch(:,loc_fbus) == i);
            % % bus power
            % % PCC bus
            if isempty(Upline) && ~isempty(Downline)
                model.sub_problem.cons = model.sub_problem.cons + ( ...
                    (var_2st.primal.bus.p_bus(:,i) == ...
                    var_2st.primal.pcc.p(:,1) - ...
                    var_2st.primal.pcc.p(:,2) + ...
                    var_2st.primal.bus.p_res(:,i) + ...
                    var_2st.primal.bus.p_es(:,i) + ...
                    var_2st.primal.bus.p_gt(:,i) - ...
                    var_2st.primal.bus.p_eb(:,i) - ...
                    var_2st.primal.bus.p_load(:,i)) : ...
                    'p of bus PCC'); %#ok<*BDSCA>
                model.sub_problem.cons = model.sub_problem.cons + ( ...
                    (var_2st.primal.bus.q_bus(:,i) == ...
                    var_2st.primal.pcc.q(:,1) - ...
                    var_2st.primal.pcc.q(:,2) - ...
                    var_2st.primal.bus.p_load(:,i)) :  ...
                    'q of bus PCC');
                % % intersaction node & load node
            else
                model.sub_problem.cons = model.sub_problem.cons + ( ...
                    (var_2st.primal.bus.p_bus(:,i) == ...
                    var_2st.primal.bus.p_res(:,i) + ...
                    var_2st.primal.bus.p_es(:,i) + ...
                    var_2st.primal.bus.p_gt(:,i) - ...
                    var_2st.primal.bus.p_eb(:,i) - ...
                    var_2st.primal.bus.p_load(:,i)) : ...
                    'p of bus PCC');
                model.sub_problem.cons = model.sub_problem.cons + ( ...
                    (var_2st.primal.bus.q_bus(:,i) == ...
                    -var_2st.primal.bus.q_load(:,i)) : ...
                    'q of bus PCC');
            end
            
            % % bus balance
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.bus.p_bus(:,i) + ...
                sum(var_2st.primal.branch.p(:,Upline), 2) == ...
                sum(var_2st.primal.branch.p(:,Downline), 2)) : ...
                'p balance of bus');
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.bus.q_bus(:,i) + ...
                sum(var_2st.primal.branch.q(:,Upline), 2) == ...
                sum(var_2st.primal.branch.q(:,Downline), 2)) : ...
                'q balance of bus');
        end
        
        % % Equation of vol
        for i = 1:num_bus
            Upline = find(data.grid.branch(:,loc_tbus) == i);
            Upbus = data.grid.branch(Upline, loc_fbus);
            if data.grid.bus(i,loc_bustype) == 3  % bus of PCC
                model.sub_problem.cons = model.sub_problem.cons + ( ...
                    (var_2st.primal.bus.vol_bus(:,i) == 1) : ...
                    'Vol of PCC');
            else
                model.sub_problem.cons = model.sub_problem.cons + ( ...
                    (var_2st.primal.bus.vol_bus(:,i) == ...
                    var_2st.primal.bus.vol_bus(:,Upbus) - ...
                    1/baseKV^2*1e-3* ...
                    (data.grid.branch(Upbus, loc_r)* ...
                    var_2st.primal.branch.p(:,Upline) + ...
                    data.grid.branch(Upbus, loc_x)* ...
                    var_2st.primal.branch.q(:,Upline))) : ...
                    'Vol of bus');
            end
            
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (data.grid.bus(i,loc_volmin) <= ...
                var_2st.primal.bus.vol_bus(:,i) <= ...
                data.grid.bus(i,loc_volmax)) : ...
                'limit of vol_bus');
        end
        
    end

%% -------------------- Equations of bus & device ------------------
    function model_equBusDevice()
        if ~isempty(setdiff(complete_busset,busset_res))
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.bus.p_res ...
                (:,setdiff(complete_busset,busset_res)) == 0) : ...
                '');
        end
        if ~isempty(setdiff(complete_busset,busset_es))
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.bus.p_es ...
                (:,setdiff(complete_busset,busset_es)) == 0) : ...
                '');
        end
        if ~isempty(setdiff(complete_busset,busset_gt))
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.bus.p_gt ...
                (:,setdiff(complete_busset,busset_gt)) == 0) : ...
                '');
        end
        if ~isempty(setdiff(complete_busset,busset_eb))
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.bus.p_eb ...
                (:,setdiff(complete_busset,busset_eb)) == 0) : ...
                '');
        end
        % % Bus with device
        if ~isempty(set_res)
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.bus.p_res(:,busset_res) == ...
                var_2st.primal.res.p) : ...
                '');
        end
        if ~isempty(set_es)
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.bus.p_es(:,busset_es) == ...
                var_2st.primal.es.p_dis - var_2st.primal.es.p_chr) : ...
                '');
        end
        if ~isempty(set_gt)
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.bus.p_gt(:,busset_gt) == ...
                var_2st.primal.gt.p) : ...
                '');
        end
        if ~isempty(set_eb)
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.bus.p_eb(:,busset_eb) == ...
                var_2st.primal.eb.p) : ...
                '');
        end
    end

%% -------------------------- PCC ----------------------------------
    function model_pcc()
        model.sub_problem.cons = model.sub_problem.cons + ( ...
            (0 <= var_2st.primal.pcc.p <= ...
            data.grid.p_pcc) : '');
        model.sub_problem.cons = model.sub_problem.cons + ( ...
            (0 <= var_2st.primal.pcc.q <= ...
            data.grid.p_pcc) : '');
    end

%% -------------------------- Device -------------------------------
    function model_device()
        % % res  默认功率数据顺序与设备数据顺序相一致
        % % res
        if ~isempty(set_res)
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (0 <= var_2st.primal.res.p <= ...
                var_2st.primal.res.p_fore) : ...
                '');
        end
        % % es
        if ~isempty(set_es)
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.es.p_chr == var_1st.base.es.p_chr) : ...
                '');
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.es.p_dis == var_1st.base.es.p_dis) : ...
                '');     
        end
        % % tst
        if ~isempty(set_tst)
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.tst.h_chr == var_1st.base.tst.h_chr) : ...
                '');
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.tst.h_dis == var_1st.base.tst.h_dis) : ...
                '');     
        end
        
        % % gt
        if ~isempty(set_gt)
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_1st.base.gt.state.* ...
                (ones(num_period,1)*data.device.param(set_gt, loc_pmin)') <= ...
                var_2st.primal.gt.p <= ...
                var_1st.base.gt.state.* ...
                (ones(num_period,1)*data.device.param(set_gt, loc_pmax)') ...
                ) : 'limit on p of gt');
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.gt.h == ...
                ones(num_period,1)* ...
                data.device.param(set_gt, loc_gt_etahr)'.* ...
                (1./data.device.param(set_gt, loc_gt_eta)' - 1 - ...
                data.device.param(set_gt, loc_gt_loss)').* ...
                var_2st.primal.gt.p ...
                ) : 'h-p of gt');
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.gt.gas == ...
                (ones(num_period, 1)*data.device.param(set_gt, loc_gt_eta)') .* ...
                var_2st.primal.gt.p ...
                ) : 'gas of gt');
        end
        
        % % eb
        if ~isempty(set_eb)
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (0 <= var_2st.primal.eb.p <= ...
                ones(num_period,1)*data.device.param(set_eb, loc_pmax)') : ...
                'limit on p of eb');
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.eb.h == ...
                (ones(num_period,1)*data.device.param(set_eb, loc_eb_eta)').* ...
                (var_2st.primal.eb.p)) : ...
                'h of eb');
        end
    end
%% ---------------------------- Cost -------------------------------
    function model_cost()
        % % grid
        model.sub_problem.cons = model.sub_problem.cons + ( ...
            (var_2st.primal.cost.grid_buy == ...
            data.grid.price(loc_gridprice_buy,:)'.* ...
            var_2st.primal.pcc.p(:,1)) : ...
            'cost of grid_buy');
        model.sub_problem.cons = model.sub_problem.cons + ( ...
            (var_2st.primal.cost.grid_sell == ...
            data.grid.price(loc_gridprice_sell,:)'.* ...
            var_2st.primal.pcc.p(:,2)) : ...
            'cost of grid_sell');
        
        % % res
        if ~isempty(set_res)
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.cost.res(:,1) == ...
                var_2st.primal.res.p(:,:)*data.device.cost(set_res, loc_c1) + ...
                ones(num_period, length(set_res))*data.device.cost(set_res, loc_c0) + ...
                var_2st.primal.res.p(:,:)*data.device.cost(set_res, loc_om)) : ...
                'cost of res');
        else
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.cost.res(:,1) == 0) : ...
                'cost of res');
        end
        
%         % % es
%         if ~isempty(set_es)
%             model.sub_problem.cons = model.sub_problem.cons + ( ...
%                 (var_2st.primal.cost.es(:,1) == ...
%                 var_2st.primal.es.p_chr(:,:)*data.device.cost(set_es, loc_om) + ...
%                 var_2st.primal.es.p_dis(:,:)*data.device.cost(set_es, loc_om)) : ...
%                 'cost of es');
%         else
%             model.sub_problem.cons = model.sub_problem.cons + ( ...
%                 (var_2st.primal.cost.es(:,1) == 0) : ...
%                 'cost of es');
%         end
        
        % % gt
        if ~isempty(set_gt)
            model.sub_problem.cons = model.sub_problem.cons + (...
                (var_2st.primal.cost.gt(:,1) == ...
                var_2st.primal.gt.gas(:,:)*data.device.cost(set_gt, loc_c1) + ...
                var_2st.primal.gt.p(:,:)*data.device.cost(set_gt, loc_om)) : ...
                'cost of gt');
        else
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.cost.gt(:,1) == 0) : ...
                'cost of gt');
        end
        
        % % eb
        if ~isempty(set_eb)
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.cost.eb(:,1) == ...
                var_2st.primal.eb.p(:,:)*data.device.cost(set_eb, loc_om)) : ...
                'cost of eb');
        else
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.cost.eb(:,1) == 0) : ...
                'cost of eb');
        end
%         model.sub_problem.cons = model.sub_problem.cons + ( ...
%             (var_1st.base.cost >= ...
%             sum(var_2st.primal.cost.grid_buy) - ...
%             sum(var_2st.primal.cost.grid_sell) + ...
%             sum(var_2st.primal.cost.res) + ...
%             sum(var_2st.primal.cost.gt) + ...
%             sum(var_2st.primal.cost.eb)) : '');
    end
end