function model_heatingwork_2st(varargin)
if find(strcmp(varargin, 'DisplayTime'))
    DisplayTime = varargin{find(strcmp(varargin, 'DisplayTime'))+1};
else
    DisplayTime = 1;
end
if DisplayTime
    fprintf('%-40s\t\t','- Model heating network');
    t0 = clock;
end
%%
global data model var_2st;
[loc_fnode, loc_tnode, loc_length, loc_diameter, loc_rough, ...
    loc_conductivity, loc_massflow] = deal(1,2,3,4,5,6,9);    % pipe
[loc_nodeno, loc_nodetype, loc_Tsmin, loc_Tsmax, loc_Trmin, loc_Trmax] = ...
    deal(1,2,3,4,5,6);                                        % node
[loc_initial_Tau_s, loc_initial_Tau_r, loc_initial_Tau_amb] = ...
    deal(1,2,3);
% % - Data
rho_w = 1;     % t/m^3;
c_w = 4200;  % MJ/(t*℃)
pi = 3.1416;
num_initialtime = data.num_initialtime;
num_period_heat = data.period*data.interval.electricity/data.interval.heat;
num_start = num_initialtime+1;
num_end = num_initialtime+num_period_heat;
data_pipe = data.heatingnetwork.pipe;
data_node = data.heatingnetwork.node;
data_initial = data.heatingnetwork.initial;
num_pipe = size(data_pipe,1);
num_node = size(data_node,1);
num_source = sum(data_node(:,loc_nodetype) == 0);
num_load = sum(data_node(:,loc_nodetype) == 2);
data_Tau_amb = ones(2*num_initialtime+num_period_heat,1)*data_initial(loc_initial_Tau_amb);
data.param_Tau_amb = [data_Tau_amb(end-num_initialtime:end,1); ...
    data_Tau_amb; data_Tau_amb(1:num_initialtime,1)];
%% Calculate basic parameters
Area = data_pipe(:,loc_diameter).^2*pi/4;
gamma = ceil(rho_w*Area.*data_pipe(:,loc_length)./...
    data_pipe(:,loc_massflow)./data.interval.heat) - 1;
R = (gamma + 1).*data_pipe(:,loc_massflow)*data.interval.heat;
kappa = (R - rho_w*Area.*data_pipe(:,loc_length))./...
    data_pipe(:,loc_massflow)./data.interval.heat;
beta = exp(-data_pipe(:,loc_conductivity).* ...
    data_pipe(:,loc_length)./(c_w*data_pipe(:,loc_massflow)));
%% Write in params of heating network
data.heatingnetwork.params.Area = Area;
data.heatingnetwork.params.gamma = gamma;
data.heatingnetwork.params.R = R;
data.heatingnetwork.params.kappa = kappa;
data.heatingnetwork.params.beta = beta;

%% Initialize variable
var_2st.primal.heatingnetwork.Tau_pipe_s_in(1:num_initialtime,:) = ...
    data_initial(loc_initial_Tau_s);
var_2st.primal.heatingnetwork.Tau_pipe_r_in(1:num_initialtime,:) = ...
    data_initial(loc_initial_Tau_r);
var_2st.primal.heatingnetwork.Tau_pipe_s_out(1:num_initialtime,:) = ...
    data_initial(loc_initial_Tau_s);
var_2st.primal.heatingnetwork.Tau_pipe_r_out(1:num_initialtime,:) = ...
    data_initial(loc_initial_Tau_r);
var_2st.primal.heatingnetwork.Tau_node_s(1:num_initialtime,:) = ...
    data_initial(loc_initial_Tau_s);
var_2st.primal.heatingnetwork.Tau_node_r(1:num_initialtime,:) = ...
    data_initial(loc_initial_Tau_r);
var_2st.primal.heatingnetwork.h_source(1:num_initialtime,:) = 0;
var_2st.primal.heatingnetwork.h_load(1:num_initialtime,:) = 0;

%% Temperature quasi-dynamic
t = num_start : num_end;
for j = 1:num_pipe
    model.sub_problem.cons = model.sub_problem.cons + ( ...
        (var_2st.primal.heatingnetwork.Tau_pipe_s_out(t,j) == ...
        (1-beta(j)) * data.param_Tau_amb(t) + ...
        beta(j) * ...
        ((1-kappa(j)) * ...
        var_2st.primal.heatingnetwork.Tau_pipe_s_in(t-gamma(j)-1,j) + ...
        kappa(j) * ...
        var_2st.primal.heatingnetwork.Tau_pipe_s_in(t-gamma(j),j))) : ...
        'heatingsys: supply Tau of pipe ');
    model.sub_problem.cons = model.sub_problem.cons + ( ...
        (var_2st.primal.heatingnetwork.Tau_pipe_r_out(t,j) == ...
        (1-beta(j)) * data.param_Tau_amb(t) + ...
        beta(j) * ...
        ((1-kappa(j)) * ...
        var_2st.primal.heatingnetwork.Tau_pipe_r_in(t-gamma(j)-1,j) + ...
        kappa(j) * ...
        var_2st.primal.heatingnetwork.Tau_pipe_r_in(t-gamma(j),j))) : ...
        'heatingsys: return Tau of pipe ');
end


%% Nodal balance
t = num_start : num_end;

for i = 1:num_node
    set_pipe_fnode = [];
    set_pipe_tnode = [];
    current_node = data_node(i,loc_nodeno); %% 由0节点导致的bug
    for j = 1:num_pipe
        if data_pipe(j,loc_fnode) == current_node   % pipeline from this node
            set_pipe_fnode(end+1) = j;
        elseif data_pipe(j,loc_tnode) == current_node % pipeline to this node
            set_pipe_tnode(end+1) = j;
        end
    end
    % --- Source node
    if data_node(i,loc_nodetype) == 0
        if ~isempty(set_pipe_fnode)
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.heatingnetwork.Tau_pipe_s_in(t,set_pipe_fnode) == ...
                var_2st.primal.heatingnetwork.Tau_node_s(t,i)) : ...
                ['heatingsys: suppley Tau of source node ' num2str(current_node)]);
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.heatingnetwork.Tau_pipe_r_out(t,set_pipe_fnode) == ...
                var_2st.primal.heatingnetwork.Tau_node_r(t,i)) : ...
                ['heatingsys: return Tau of source node ' num2str(current_node)]);
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.heatingnetwork.h_source(t,1) == ...
                c_w*data_pipe(set_pipe_fnode,loc_massflow)/3600*...
                (var_2st.primal.heatingnetwork.Tau_node_s(t,i) - ...
                var_2st.primal.heatingnetwork.Tau_node_r(t,i))) : ...
                ['heatingsys: power balance at source node ' num2str(current_node)]);
        end
    end
    % % --- Cross node
    if data_node(i,loc_nodetype) == 1
        % % ---- supply network
        if ~isempty(set_pipe_fnode)
            if isempty(set_pipe_tnode)
                fprintf('\n Error: There is something wrong with the data of Heating Network. (Supply Network: node %d)\n', num2str(current_node));
                return;
            end
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.heatingnetwork.Tau_pipe_s_in(t,set_pipe_fnode) == ...
                var_2st.primal.heatingnetwork.Tau_node_s(t,i)*ones(1,length(set_pipe_fnode))) : ...
                ['heatingsys: supply Tau of cross node ' num2str(current_node)]);
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.heatingnetwork.Tau_node_s(t,i)* ...
                sum(data_pipe(set_pipe_fnode,loc_massflow)) == ...
                var_2st.primal.heatingnetwork.Tau_pipe_s_out(t,set_pipe_tnode)* ...
                data_pipe(set_pipe_tnode,loc_massflow)) : ...
                ['heatingsys: power balance at supply cross node ' num2str(current_node)]);
        end
        % % ---- Return network
        if ~isempty(set_pipe_tnode)
            if isempty(set_pipe_fnode)
                fprintf('\n Error: There is something wrong with the data of Heating Network. (Return Network: node %d)\n', current_node);
                return;
            end
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.heatingnetwork.Tau_pipe_r_in(t,set_pipe_tnode) == ...
                var_2st.primal.heatingnetwork.Tau_node_r(t,i)*ones(1,length(set_pipe_tnode))) : ...
                ['heatingsys: return Tau of cross node ' num2str(current_node)]);
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.heatingnetwork.Tau_node_r(t,i)* ...
                sum(data_pipe(set_pipe_tnode,loc_massflow)) == ...
                var_2st.primal.heatingnetwork.Tau_pipe_r_out(t,set_pipe_fnode)* ...
                data_pipe(set_pipe_fnode,loc_massflow)) : ...
                ['heatingsys: power balance at return cross node ' num2str(current_node)]);
        end
    end
    % % --- Load node
    if data_node(i,loc_nodetype) == 2
        if ~isempty(set_pipe_tnode)
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.heatingnetwork.Tau_pipe_s_out(t,set_pipe_tnode) == ...
                var_2st.primal.heatingnetwork.Tau_node_s(t,i)*ones(1,length(set_pipe_tnode))) : ...
                ['heatingsys: supply Tau of load node ' num2str(current_node)]);
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.heatingnetwork.Tau_pipe_r_in(t,set_pipe_tnode) == ...
                var_2st.primal.heatingnetwork.Tau_node_r(t,i)*ones(1,length(set_pipe_tnode))) : ...
                ['heatingsys: return Tau of load node ' num2str(current_node)]);
            model.sub_problem.cons = model.sub_problem.cons + ( ...
                (var_2st.primal.heatingnetwork.h_load(t, ...
                sum(data_node(1:i,loc_nodetype) == 2)) == ...
                c_w*data_pipe(set_pipe_tnode,loc_massflow)/3600* ...
                (var_2st.primal.heatingnetwork.Tau_node_s(t,i) - ...
                var_2st.primal.heatingnetwork.Tau_node_r(t,i))) : ...
                ['heatingsys: power balance at load node ' num2str(current_node)]);
        end
    end
end

%% Node temperature limit
model.sub_problem.cons = model.sub_problem.cons + ( ...
    (var_2st.primal.heatingnetwork.Tau_node_s(:,:) >= ...
    data_node(1,loc_Tsmin)) : '');
model.sub_problem.cons = model.sub_problem.cons + ( ...
    (var_2st.primal.heatingnetwork.Tau_node_s(:,:) <= ...
    data_node(1,loc_Tsmax)) : '');
model.sub_problem.cons = model.sub_problem.cons + ( ...
    (var_2st.primal.heatingnetwork.Tau_node_r(:,:) >= ...
    data_node(1,loc_Trmin)) : '');
model.sub_problem.cons = model.sub_problem.cons + ( ...
    (var_2st.primal.heatingnetwork.Tau_node_r(:,:) <= ...
    data_node(1,loc_Trmax)) : '');

%% Final states constraints: supply temperature
model.sub_problem.cons = model.sub_problem.cons + ( ...
    (var_2st.primal.heatingnetwork.Tau_node_s(num_end,1) >= ...
    data_initial(loc_initial_Tau_s)) : '');
model.sub_problem.cons = model.sub_problem.cons + ( ...
    (var_2st.primal.heatingnetwork.Tau_node_r(num_end,1) <= ...
    data_initial(loc_initial_Tau_r)) : '');


%%
if DisplayTime
    t1 = clock;
    fprintf('%8.2f%s\n', etime(t1,t0), 's');
end
end