function model_dualProblem(varargin)
if find(strcmp(varargin, 'DisplayTime'))
    DisplayTime = varargin{find(strcmp(varargin, 'DisplayTime'))+1};
else
    DisplayTime = 1;
end
if DisplayTime
    fprintf('%-40s\t\t','- Model dual problem');
    t0 = clock;
end
%%
global data model var_2st;
big_M = 1e6;
[loc_profilestype] = deal(2);       % profiles
num_period = data.period;
set_loadpower = find(data.profiles.bus(:,loc_profilestype) == 1);
set_respower = find(data.profiles.bus(:,loc_profilestype) == 2);
details = model.sub_problem.details;
%%
model.sub_problem.dual_problem.cons = [];
model.sub_problem.dual_problem.obj = 0;
var_2st.dual = [];

%% variables
var_2st.dual.p_res = sdpvar(num_period, length(set_respower), 'full');
var_2st.dual.p_load = sdpvar(num_period, length(set_loadpower), 'full');
var_2st.dual.Tau_out = sdpvar(num_period, 1, 'full');
% %
var_2st.dual.p_res_pos = binvar(num_period, length(set_respower), 'full');
var_2st.dual.p_res_neg = binvar(num_period, length(set_respower), 'full');
var_2st.dual.p_load_pos = binvar(num_period, length(set_loadpower), 'full');
var_2st.dual.p_load_neg = binvar(num_period, length(set_loadpower), 'full');
var_2st.dual.Tau_out_pos = binvar(num_period, 1, 'full');
var_2st.dual.Tau_out_neg = binvar(num_period, 1, 'full');
% 
var_2st.dual.cost_p_res_pos = sdpvar(num_period, length(set_respower), 'full');
var_2st.dual.cost_p_res_neg = sdpvar(num_period, length(set_respower), 'full');
var_2st.dual.cost_p_load_pos = sdpvar(num_period, length(set_loadpower), 'full');
var_2st.dual.cost_p_load_neg = sdpvar(num_period, length(set_loadpower), 'full');
var_2st.dual.cost_Tau_out_pos = sdpvar(num_period, 1, 'full');
var_2st.dual.cost_Tau_out_neg = sdpvar(num_period, 1, 'full');
%% Constraints
% % uncertainty variables
model.sub_problem.dual_problem.cons = [];

model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
    (var_2st.dual.p_res_pos + var_2st.dual.p_res_neg <= 1) : '');
model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
    (var_2st.dual.p_load_pos + var_2st.dual.p_load_neg <= 1) : '');
model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
    (var_2st.dual.Tau_out_pos + var_2st.dual.Tau_out_neg <= 1) : '');

%
model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
    (sum(var_2st.dual.p_res_pos + var_2st.dual.p_res_neg, 2) == ...
    data.uncertainty.Gamma.p_res) : '');
model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
    (sum(var_2st.dual.p_load_pos + var_2st.dual.p_load_neg, 2) == ...
    data.uncertainty.Gamma.p_load) : '');
model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
    (sum(var_2st.dual.Tau_out_pos + var_2st.dual.Tau_out_neg, 1) == ...  %% 1, not 2
    data.uncertainty.Gamma.Tau_out) : '');
% p_res
model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
    (var_2st.dual.p_res(:,:) == ...
    data.profiles.data(set_respower, :)' .* ( 1 + ...
    data.uncertainty.Deviation.p_res * ...
    var_2st.dual.p_res_pos - ...
    data.uncertainty.Deviation.p_res * ...
    var_2st.dual.p_res_neg)) :   'p res'); %#ok<*FNDSB>
% % p_load
model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
    (var_2st.dual.p_load(:,:) == ...
    data.profiles.data(set_loadpower,:)' .* ( 1 + ...
    data.uncertainty.Deviation.p_load * ...
    var_2st.dual.p_load_pos - ...
    data.uncertainty.Deviation.p_load * ...
    var_2st.dual.p_load_neg)) : 'p load of bus'); %#ok<*BDSCA>
% % Tau_out
model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
    (var_2st.dual.Tau_out == ...
    data.buildings.Tau_out .* ( 1 + ...
    data.uncertainty.Deviation.Tau_out * ...
    var_2st.dual.Tau_out_pos - ...
    data.uncertainty.Deviation.Tau_out * ...
    var_2st.dual.Tau_out_neg)) : 'Tau_out');

%% Model outer problem
% % details.f(f_start_res:f_end_res) = - p_res;
% % details.f(f_start_load:f_end_load) = - p_load;
% % details.f(f_start_Tau:f_end_Tau) = - Tau_out;
f_start_res = 7301; f_end_res= 7396;
f_start_load = 7397; f_end_load = 8188;
f_start_Tau = 17699; f_end_Tau = 17722;
for i = 1:length(set_respower)
    index_res(:,i) = f_start_res + num_period*(i-1) : f_start_res+num_period*i-1; %#ok<*AGROW>
end
for i = 1:length(set_loadpower)
    index_load(:,i) = f_start_load + num_period*(i-1) : f_start_load+num_period*i-1;
end
var_2st.dual.dual_nu = sdpvar(length(details.b),1,'full');
var_2st.dual.dual_lambda = sdpvar(length(details.f),1,'full');
model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
    (-big_M <= var_2st.dual.dual_nu <= 0) : '');
model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
    (-big_M <= var_2st.dual.dual_lambda <= big_M) : '');
% % dual_nu'*A + dual_lambda'*E == c'
model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
    (details.A'*var_2st.dual.dual_nu + ...
    details.E'*var_2st.dual.dual_lambda == ...
    details.c) : '');

%% Obj
model.sub_problem.dual_problem.obj = ...
    var_2st.dual.dual_nu'*details.b + ...
    var_2st.dual.dual_lambda(1:f_start_res-1)'*details.f(1:f_start_res-1) + ...
    var_2st.dual.dual_lambda(f_end_res+1:f_start_load-1)'*details.f(f_end_res+1:f_start_load-1) + ...
    var_2st.dual.dual_lambda(f_end_load+1:f_start_Tau-1)'*details.f(f_end_load+1:f_start_Tau-1)+ ...
    var_2st.dual.dual_lambda(f_end_Tau+1:end)'*details.f(f_end_Tau+1:end);

for i = 1:length(set_respower)
    model.sub_problem.dual_problem.obj = model.sub_problem.dual_problem.obj + ...
        var_2st.dual.dual_lambda(index_res(:,i),1)' * ...
        (- var_2st.dual.p_res(:,i));
end
for i = 1:length(set_loadpower)
    model.sub_problem.dual_problem.obj = model.sub_problem.dual_problem.obj + ...
        var_2st.dual.dual_lambda(index_load(:,i),1)' * ...
        (- var_2st.dual.p_load(:,i));
end
model.sub_problem.dual_problem.obj = model.sub_problem.dual_problem.obj + ...
    var_2st.dual.dual_lambda(f_start_Tau:f_end_Tau,1)' * ...
    (-var_2st.dual.Tau_out);

%% Obj
model.sub_problem.dual_problem.obj = ...
    var_2st.dual.dual_nu'*details.b + ...
    var_2st.dual.dual_lambda(1:f_start_res-1)'*details.f(1:f_start_res-1) + ...
    var_2st.dual.dual_lambda(f_end_res+1:f_start_load-1)'*details.f(f_end_res+1:f_start_load-1) + ...
    var_2st.dual.dual_lambda(f_end_load+1:f_start_Tau-1)'*details.f(f_end_load+1:f_start_Tau-1)+ ...
    var_2st.dual.dual_lambda(f_end_Tau+1:end)'*details.f(f_end_Tau+1:end);
% % fixed cost
for i = 1:length(set_respower)
    model.sub_problem.dual_problem.obj = model.sub_problem.dual_problem.obj + ...
        var_2st.dual.dual_lambda(index_res(:,i),1)' * ...
        (-data.profiles.data(set_respower(i), :)');
end
for i = 1:length(set_loadpower)
    model.sub_problem.dual_problem.obj = model.sub_problem.dual_problem.obj + ...
        var_2st.dual.dual_lambda(index_load(:,i),1)' * ...
        (-data.profiles.data(set_loadpower(i), :)');
end
model.sub_problem.dual_problem.obj = model.sub_problem.dual_problem.obj + ...
    var_2st.dual.dual_lambda(f_start_Tau:f_end_Tau,1)' * ...
    (-data.profiles.data(data.profiles.bus(:,loc_profilestype)==3,:)');

%% p_res
% % cost of res deviation
for i = 1:length(set_respower)
    % % cost_p_pos
    model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
        (-data.uncertainty.Deviation.p_res * ...
        data.profiles.data(set_respower(i), :)'.* ...
        var_2st.dual.dual_lambda(index_res(:,i),1) - ...
        big_M*(1-var_2st.dual.p_res_pos(:,i)) <= ...
        ...
        var_2st.dual.cost_p_res_pos(:,i) <= ...
        ...
        -data.uncertainty.Deviation.p_res * ...
        data.profiles.data(set_respower(i), :)'.* ...
        var_2st.dual.dual_lambda(index_res(:,i),1) + ...
        big_M*(1-var_2st.dual.p_res_pos(:,i))) : '');
    
    model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
        (-big_M*var_2st.dual.p_res_pos(:,i) <= ...
        var_2st.dual.cost_p_res_pos(:,i) <= ...
        big_M*var_2st.dual.p_res_pos(:,i)) : '');
    
    % % cost_p_res_neg
    model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
        (data.uncertainty.Deviation.p_res * ...
        data.profiles.data(set_respower(i), :)'.* ...
        var_2st.dual.dual_lambda(index_res(:,i),1) - ...
        big_M*(1-var_2st.dual.p_res_neg(:,i)) <= ...
        ...
        var_2st.dual.cost_p_res_neg(:,i) <= ...
        ...
        data.uncertainty.Deviation.p_res * ...
        data.profiles.data(set_respower(i), :)'.* ...
        var_2st.dual.dual_lambda(index_res(:,i),1) + ...
        big_M*(1-var_2st.dual.p_res_neg(:,i))) : '');
    
    model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
        (-big_M*var_2st.dual.p_res_neg(:,i) <= ...
        var_2st.dual.cost_p_res_neg(:,i) <= ...
        big_M*var_2st.dual.p_res_neg(:,i)) : ''); 
end

%% p_load
% % cost of load deviation
for i = 1:length(set_loadpower)
    % cost_p_load_pos == -lambda*p_res*deviation or 0
    model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
        (-data.uncertainty.Deviation.p_load * ...
        data.profiles.data(set_loadpower(i), :)'.*  ...
        var_2st.dual.dual_lambda(index_load(:,i),1) - ...
        big_M*(1-var_2st.dual.p_load_pos(:,set_loadpower(i))) <= ...
        ...
        var_2st.dual.cost_p_load_pos(:,i) <= ...
        ...
        -data.uncertainty.Deviation.p_load * ...
        data.profiles.data(set_loadpower(i), :)'.*  ...
        var_2st.dual.dual_lambda(index_load(:,i),1) + ...
        big_M*(1-var_2st.dual.p_load_pos(:,set_loadpower(i)))) : '');
    
    model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
        (-big_M*var_2st.dual.p_load_pos(:,set_loadpower(i)) ....
        <= var_2st.dual.cost_p_load_pos(:,i) <= ...
        big_M*var_2st.dual.p_load_pos(:,set_loadpower(i))) : '');
    
    % cost_p_load_neg == -lambda*p_res*deviation or 0
    model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
        (data.uncertainty.Deviation.p_load * ...
        data.profiles.data(set_loadpower(i), :)' .* ...
        var_2st.dual.dual_lambda(index_load(:,i),1) - ...
        big_M*(1-var_2st.dual.p_load_neg(:,set_loadpower(i))) <= ....
        ...
        var_2st.dual.cost_p_load_neg(:,i) <= ...
        ...
        data.uncertainty.Deviation.p_load * ...
        data.profiles.data(set_loadpower(i), :)' .*  ...
        var_2st.dual.dual_lambda(index_load(:,i),1) + ...
        big_M*(1-var_2st.dual.p_load_neg(:,set_loadpower(i)))) : '');
    
    model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
        (-big_M*var_2st.dual.p_load_neg(:,set_loadpower(i)) ....
        <= var_2st.dual.cost_p_load_neg(:,i) <= ...
        big_M*var_2st.dual.p_load_neg(:,set_loadpower(i))) : '');
end

%% Tau_out
% % cost of Tau deviation
% cost_Tau_out_pos == -lambda*p_res*deviation or 0
model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
    (-data.uncertainty.Deviation.Tau_out * ...
    data.profiles.data(data.profiles.bus(:,loc_profilestype)==3,:)' .* ...
    var_2st.dual.dual_lambda(f_start_Tau:f_end_Tau, 1) - ...
    big_M*(1-var_2st.dual.Tau_out_pos) <=  ....
    ...
    var_2st.dual.cost_Tau_out_pos <= ...
    ...
    -data.uncertainty.Deviation.Tau_out * ...
    data.profiles.data(data.profiles.bus(:,loc_profilestype)==3,:)' .* ...
    var_2st.dual.dual_lambda(f_start_Tau:f_end_Tau, 1) + ...
    big_M*(1-var_2st.dual.Tau_out_pos)) : '');

model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
    (-big_M*var_2st.dual.Tau_out_pos ....
    <= var_2st.dual.cost_Tau_out_pos <= ...
    big_M*var_2st.dual.Tau_out_pos) : '');

% cost_Tau_out_neg == -lambda*p_res*deviation or 0
model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
    (data.uncertainty.Deviation.Tau_out * ...
    data.profiles.data(data.profiles.bus(:,loc_profilestype)==3,:)' .* ...
    var_2st.dual.dual_lambda(f_start_Tau:f_end_Tau, 1) - ...
    big_M*(1-var_2st.dual.Tau_out_neg) ....
    ...
    <= var_2st.dual.cost_Tau_out_neg <= ...
    ...
    data.uncertainty.Deviation.Tau_out * ...
    data.profiles.data(data.profiles.bus(:,loc_profilestype)==3,:)' .* ...
    var_2st.dual.dual_lambda(f_start_Tau:f_end_Tau, 1) + ...
    big_M*(1-var_2st.dual.Tau_out_neg)) : '');

model.sub_problem.dual_problem.cons = model.sub_problem.dual_problem.cons + ( ...
    (-big_M*var_2st.dual.Tau_out_neg ....
    <= var_2st.dual.cost_Tau_out_neg <= ...
    big_M*var_2st.dual.Tau_out_neg) : '');

%% Obj
model.sub_problem.dual_problem.obj = model.sub_problem.dual_problem.obj + ...
    sum(sum(var_2st.dual.cost_p_res_pos + var_2st.dual.cost_p_res_neg)) + ...
    sum(sum(var_2st.dual.cost_p_load_pos + var_2st.dual.cost_p_load_neg)) + ...
    sum(var_2st.dual.cost_Tau_out_pos + var_2st.dual.cost_Tau_out_neg);

%%
if DisplayTime
    t1 = clock;
    fprintf('%8.2f%s\n', etime(t1,t0), 's');
end
end