function model_BLP_mainProblem(varargin)
if find(strcmp(varargin, 'DisplayTime'))
    DisplayTime = varargin{find(strcmp(varargin, 'DisplayTime'))+1};
else
    DisplayTime = 1;
end
if DisplayTime
    fprintf('%-40s\t\t','- Model BLP main problem');
    t0 = clock;
end
%%
global data model var_2st big_M;
[loc_profilestype] = deal(2);       % profiles
num_period = data.period;
num_building = size(data.buildings.param,1);
set_loadpower = find(data.profiles.bus(:,loc_profilestype) == 1);
set_respower = find(data.profiles.bus(:,loc_profilestype) == 2);
details = model.sub_problem.details;

%%
model.sub_problem.BLP.main_problem.cons = [];
model.sub_problem.BLP.main_problem.obj = 0;
var_2st.BLP.main_problem = [];
var_2st.BLP.main_problem.details = details;
%% Variables
var_2st.BLP.main_problem.p_res = sdpvar(num_period, length(set_respower), 'full');
var_2st.BLP.main_problem.p_load = sdpvar(num_period, length(set_loadpower), 'full');
var_2st.BLP.main_problem.Tau_out = sdpvar(num_period, 1, 'full');
var_2st.BLP.main_problem.Tau_act = sdpvar(num_period, num_building, 'full');
% %
var_2st.BLP.main_problem.p_res_pos = sdpvar(num_period, length(set_respower), 'full');
var_2st.BLP.main_problem.p_res_neg = sdpvar(num_period, length(set_respower), 'full');
var_2st.BLP.main_problem.p_load_pos = sdpvar(num_period, length(set_loadpower), 'full');
var_2st.BLP.main_problem.p_load_neg = sdpvar(num_period, length(set_loadpower), 'full');
var_2st.BLP.main_problem.Tau_out_pos = sdpvar(num_period, 1, 'full');
var_2st.BLP.main_problem.Tau_out_neg = sdpvar(num_period, 1, 'full');
var_2st.BLP.main_problem.Tau_act_pos = sdpvar(num_period, num_building, 'full');
var_2st.BLP.main_problem.Tau_act_neg = sdpvar(num_period, num_building, 'full');
%
for k = 1:length(model.sub_problem.BLP.scenario)
    var_2st.BLP.main_problem.cost_bilinear(k).p_res = sdpvar(num_period, length(set_respower), 'full');
    var_2st.BLP.main_problem.cost_bilinear(k).p_load = sdpvar(num_period, length(set_loadpower), 'full');
    var_2st.BLP.main_problem.cost_bilinear(k).Tau_out = sdpvar(num_period, 1, 'full');
    var_2st.BLP.main_problem.cost_bilinear(k).Tau_act = sdpvar(num_period, num_building, 'full');
    var_2st.BLP.main_problem.cost_bilinear(k).total_cost = sdpvar(1,1,'full');
end
var_2st.BLP.main_problem.cost_bilinear_min = sdpvar(1,1,'full');
%% Unceratinty constraints
% uncertainty
% % p_res
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (0 <= var_2st.BLP.main_problem.p_res_pos <= 1) : '');
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (0 <= var_2st.BLP.main_problem.p_res_neg <= 1) : '');
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (sum(var_2st.BLP.main_problem.p_res_pos, 1) == ...
    sum(var_2st.BLP.main_problem.p_res_neg, 1)) : '');
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (sum(var_2st.BLP.main_problem.p_res_pos, 1) + ...
    sum(var_2st.BLP.main_problem.p_res_neg, 1) <= ...
    data.uncertainty.Gamma.p_res) : '');

% % p_load
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (0 <= var_2st.BLP.main_problem.p_load_pos <= 1) : '');
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (0 <= var_2st.BLP.main_problem.p_load_neg <= 1) : '');
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (sum(var_2st.BLP.main_problem.p_load_pos, 1) == ...
    sum(var_2st.BLP.main_problem.p_load_neg, 1)) : '');
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (sum(var_2st.BLP.main_problem.p_load_pos, 1) + ...
    sum(var_2st.BLP.main_problem.p_load_neg, 1) <= ...
    data.uncertainty.Gamma.p_load) : '');

% % Tau_out
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (0 <= var_2st.BLP.main_problem.Tau_out_pos <= 1) : '');
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (0 <= var_2st.BLP.main_problem.Tau_out_neg <= 1) : '');
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (sum(var_2st.BLP.main_problem.Tau_out_pos, 1) == ...
    sum(var_2st.BLP.main_problem.Tau_out_neg, 1)) : '');
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (sum(var_2st.BLP.main_problem.Tau_out_pos, 1) + ...
    sum(var_2st.BLP.main_problem.Tau_out_neg, 1) <= ...
    data.uncertainty.Gamma.Tau_out) : '');

% % Tau_act
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (0 <= var_2st.BLP.main_problem.Tau_act_pos <= 1) : '');
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (0 <= var_2st.BLP.main_problem.Tau_act_neg <= 1) : '');
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (sum(var_2st.BLP.main_problem.Tau_act_pos, 1) == ...
    sum(var_2st.BLP.main_problem.Tau_act_neg, 1)) : '');
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (sum(var_2st.BLP.main_problem.Tau_act_pos, 1) + ...
    sum(var_2st.BLP.main_problem.Tau_act_neg, 1) <= ...
    data.uncertainty.Gamma.Tau_act) : '');

% %
% % p_res
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (sum(var_2st.BLP.main_problem.p_res_pos + ...
    var_2st.BLP.main_problem.p_res_neg, 1) <= ...
    data.uncertainty.Gamma.p_res) : '');
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (sum(var_2st.BLP.main_problem.p_res_pos, 1) == ...
    sum(var_2st.BLP.main_problem.p_res_neg, 1)) : '');
% % p_load
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (sum(var_2st.BLP.main_problem.p_load_pos,1) == ...
    sum(var_2st.BLP.main_problem.p_load_neg, 1)) : '');
% % Tau_out
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (sum(var_2st.BLP.main_problem.Tau_out_pos,1) == ...
    sum(var_2st.BLP.main_problem.Tau_out_neg, 1)) : '');
% % Tau_act
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (sum(var_2st.BLP.main_problem.Tau_act_pos,1) == ...
    sum(var_2st.BLP.main_problem.Tau_act_neg, 1)) : '');
% % 
% % p_res
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (var_2st.BLP.main_problem.p_res(:,:) == ...
    data.profiles.data(set_respower, :)' .* ...
    ( 1 + ...
    data.uncertainty.Deviation.p_res * ...
    var_2st.BLP.main_problem.p_res_pos - ...
    data.uncertainty.Deviation.p_res * ...
    var_2st.BLP.main_problem.p_res_neg)) :   'p res');
% % p_load
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (var_2st.BLP.main_problem.p_load(:,:) == ...
    data.profiles.data(set_loadpower,:)' .* ( 1 + ...
    data.uncertainty.Deviation.p_load * ...
    var_2st.BLP.main_problem.p_load_pos - ...
    data.uncertainty.Deviation.p_load * ...
    var_2st.BLP.main_problem.p_load_neg)) : 'p load of bus');
% % Tau_out
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (var_2st.BLP.main_problem.Tau_out == ...
    data.buildings.Tau_out .* ( 1 + ...
    data.uncertainty.Deviation.Tau_out * ...
    var_2st.BLP.main_problem.Tau_out_pos - ...
    data.uncertainty.Deviation.Tau_out * ...
    var_2st.BLP.main_problem.Tau_out_neg)) : 'Tau_out');
% % Tau_act
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (var_2st.BLP.main_problem.Tau_act == ...
    data.buildings.Tau_act' .* ( 1 + ...
    data.uncertainty.Deviation.Tau_act * ...
    var_2st.BLP.main_problem.Tau_act_pos - ...
    data.uncertainty.Deviation.Tau_act * ...
    var_2st.BLP.main_problem.Tau_act_neg)) : 'Tau_act');

%% Dual constraints
f_start_res = 7441; f_end_res= 7536;                    % 7441   7536
f_start_load = 7537; f_end_load = 8328;                 % 7537   8328
f_start_Tau_out = 17815; f_end_Tau_out = 17838;         % 17815  17838
f_start_Tau_act = 17839; f_end_Tau_act = 18462;         % 17839  18462
for i = 1:length(set_respower)
    index_res(:,i) = f_start_res + num_period*(i-1) : f_start_res+num_period*i-1; %#ok<*AGROW>
end
for i = 1:length(set_loadpower)
    index_load(:,i) = f_start_load + num_period*(i-1) : f_start_load+num_period*i-1;
end
index_Tau_out = f_start_Tau_out:f_end_Tau_out;
for i = 1:num_building
    index_Tau_act(:,i) = f_start_Tau_act + num_period*(i-1) : f_start_Tau_act+num_period*i-1;
end
var_2st.BLP.main_problem.dual_nu = sdpvar(length(details.b),1,'full');
var_2st.BLP.main_problem.dual_lambda = sdpvar(length(details.f),1,'full');
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (-big_M <= var_2st.BLP.main_problem.dual_nu <= 0) : '');
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (-big_M <= var_2st.BLP.main_problem.dual_lambda <= big_M) : '');
% % dual_nu'*A + dual_lambda'*E == c'
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    (details.A'*var_2st.BLP.main_problem.dual_nu + ...
    details.E'*var_2st.BLP.main_problem.dual_lambda == ...
    details.c) : '');

%% cost_bilinear constraints
% model.sub_problem.BLP.main_problem.cons = ...
%     model.sub_problem.BLP.main_problem.cons + ( ...
%     (-big_M <= var_2st.BLP.main_problem.cost_bilinear_min <= big_M) : '');
for k = 1:length(model.sub_problem.BLP.scenario)
    % % res
    for i = 1:length(set_respower)
        model.sub_problem.BLP.main_problem.cons = ...
            model.sub_problem.BLP.main_problem.cons + ( ...
            ( var_2st.BLP.main_problem.cost_bilinear(k).p_res(:,i) == ...
            -data.profiles.data(set_respower(i),:)' .* ...
            (var_2st.BLP.main_problem.dual_lambda(index_res(:,i),1) + ...
            ...
            data.uncertainty.Deviation.p_res * ...
            (var_2st.BLP.main_problem.dual_lambda(index_res(:,i),1) .* ...
            model.sub_problem.BLP.scenario(k).uncertainty.p_res_pos(:,i) + ...
            var_2st.BLP.main_problem.p_res_pos(:,i) .* ...
            model.sub_problem.BLP.scenario(k).lambda.p_res(:,i) - ...
            model.sub_problem.BLP.scenario(k).uncertainty.p_res_pos(:,i) .* ...
            model.sub_problem.BLP.scenario(k).lambda.p_res(:,i)) + ...
            ...
            -data.uncertainty.Deviation.p_res * ...
            (var_2st.BLP.main_problem.dual_lambda(index_res(:,i),1) .* ...
            model.sub_problem.BLP.scenario(k).uncertainty.p_res_neg(:,i) + ...
            var_2st.BLP.main_problem.p_res_neg(:,i) .* ...
            model.sub_problem.BLP.scenario(k).lambda.p_res(:,1) - ...
            model.sub_problem.BLP.scenario(k).uncertainty.p_res_neg(:,i) .* ...
            model.sub_problem.BLP.scenario(k).lambda.p_res(:,1))) ...
            ) : '');
    end
    % % load
    for i = 1:length(set_loadpower)
        model.sub_problem.BLP.main_problem.cons = ...
            model.sub_problem.BLP.main_problem.cons + ( ...
            ( var_2st.BLP.main_problem.cost_bilinear(k).p_load(:,i) == ...
            -data.profiles.data(set_loadpower(i),:)' .* ...
            (var_2st.BLP.main_problem.dual_lambda(index_load(:,i),1) + ...
            ...
            data.uncertainty.Deviation.p_load * ...
            (var_2st.BLP.main_problem.dual_lambda(index_load(:,i),1) .* ...
            model.sub_problem.BLP.scenario(k).uncertainty.p_load_pos(:,i) + ...
            var_2st.BLP.main_problem.p_load_pos(:,i) .* ...
            model.sub_problem.BLP.scenario(k).lambda.p_load(:,i) - ...
            model.sub_problem.BLP.scenario(k).uncertainty.p_load_pos(:,i) .* ...
            model.sub_problem.BLP.scenario(k).lambda.p_load(:,i)) + ...
            ...
            -data.uncertainty.Deviation.p_load * ...
            (var_2st.BLP.main_problem.dual_lambda(index_load(:,i),1) .* ...
            model.sub_problem.BLP.scenario(k).uncertainty.p_load_neg(:,i) + ...
            var_2st.BLP.main_problem.p_load_neg(:,i) .* ...
            model.sub_problem.BLP.scenario(k).lambda.p_load(:,i) - ...
            model.sub_problem.BLP.scenario(k).uncertainty.p_load_neg(:,i) .* ...
            model.sub_problem.BLP.scenario(k).lambda.p_load(:,i))) ...
            ) : '');
    end
    % % Tau_out
    model.sub_problem.BLP.main_problem.cons = ...
        model.sub_problem.BLP.main_problem.cons + ( ...
        ( var_2st.BLP.main_problem.cost_bilinear(k).Tau_out == ...
        -data.profiles.data(data.profiles.bus(:,loc_profilestype) == 3,:)' .* ...
        (var_2st.BLP.main_problem.dual_lambda(index_Tau_out,1) + ...
        ...
        data.uncertainty.Deviation.Tau_out * ...
        (var_2st.BLP.main_problem.dual_lambda(index_Tau_out,1) .* ...
        model.sub_problem.BLP.scenario(k).uncertainty.Tau_out_pos + ...
        var_2st.BLP.main_problem.Tau_out_pos .* ...
        model.sub_problem.BLP.scenario(k).lambda.Tau_out - ...
        model.sub_problem.BLP.scenario(k).uncertainty.Tau_out_pos .* ...
        model.sub_problem.BLP.scenario(k).lambda.Tau_out) + ...
        ...
        -data.uncertainty.Deviation.Tau_out * ...
        (var_2st.BLP.main_problem.dual_lambda(index_Tau_out,1).* ...
        model.sub_problem.BLP.scenario(k).uncertainty.Tau_out_neg + ...
        var_2st.BLP.main_problem.Tau_out_neg .* ...
        model.sub_problem.BLP.scenario(k).lambda.Tau_out - ...
        model.sub_problem.BLP.scenario(k).uncertainty.Tau_out_neg .* ...
        model.sub_problem.BLP.scenario(k).lambda.Tau_out)) ...
        ) : '');
    
    % % Tau_act
    for i = 1:num_building
        model.sub_problem.BLP.main_problem.cons = ...
            model.sub_problem.BLP.main_problem.cons + ( ...
            ( var_2st.BLP.main_problem.cost_bilinear(k).Tau_act(:,i) == ...
            -data.buildings.Tau_act(i,:)' .* ...
            (var_2st.BLP.main_problem.dual_lambda(index_Tau_act(:,i),1) + ...
            ...
            data.uncertainty.Deviation.Tau_act * ...
            (var_2st.BLP.main_problem.dual_lambda(index_Tau_act(:,i),1) .* ...
            model.sub_problem.BLP.scenario(k).uncertainty.Tau_act_pos(:,i) + ...
            var_2st.BLP.main_problem.Tau_act_pos(:,i) .* ...
            model.sub_problem.BLP.scenario(k).lambda.Tau_act(:,i) - ...
            model.sub_problem.BLP.scenario(k).uncertainty.Tau_act_pos(:,i) .* ...
            model.sub_problem.BLP.scenario(k).lambda.Tau_act(:,i)) + ...
            ...
            -data.uncertainty.Deviation.Tau_act * ...
            (var_2st.BLP.main_problem.dual_lambda(index_Tau_act(:,i),1).* ...
            model.sub_problem.BLP.scenario(k).uncertainty.Tau_act_neg(:,i) + ...
            var_2st.BLP.main_problem.Tau_act_neg(:,i) .* ...
            model.sub_problem.BLP.scenario(k).lambda.Tau_act(:,i) - ...
            model.sub_problem.BLP.scenario(k).uncertainty.Tau_act_neg(:,i) .* ...
            model.sub_problem.BLP.scenario(k).lambda.Tau_act(:,i))) ...
            ) : '');
    end
end
for k = 1:length(model.sub_problem.BLP.scenario)
    model.sub_problem.BLP.main_problem.cons = ...
        model.sub_problem.BLP.main_problem.cons + ( ...
        (var_2st.BLP.main_problem.cost_bilinear(k).total_cost == ...
        sum(sum(var_2st.BLP.main_problem.cost_bilinear(k).p_res)) + ...
        sum(sum(var_2st.BLP.main_problem.cost_bilinear(k).p_load)) + ...
        sum(sum(var_2st.BLP.main_problem.cost_bilinear(k).Tau_out)) + ...
        sum(sum(var_2st.BLP.main_problem.cost_bilinear(k).Tau_act)) ...
        ) : '');
end
for k = 1:length(model.sub_problem.BLP.scenario)
    model.sub_problem.BLP.main_problem.cons = ...
        model.sub_problem.BLP.main_problem.cons + ( ...
        (var_2st.BLP.main_problem.cost_bilinear_min <= ...
        var_2st.BLP.main_problem.cost_bilinear(k).total_cost ...
        ) : '');
end

%% Obj
model.sub_problem.BLP.main_problem.obj = ...
    var_2st.BLP.main_problem.dual_nu'*details.b + ...
    var_2st.BLP.main_problem.dual_lambda(1:f_start_res-1)'*details.f(1:f_start_res-1) + ...
    var_2st.BLP.main_problem.dual_lambda(f_end_res+1:f_start_load-1)'*details.f(f_end_res+1:f_start_load-1) + ...
    var_2st.BLP.main_problem.dual_lambda(f_end_load+1:f_start_Tau_out-1)'*details.f(f_end_load+1:f_start_Tau_out-1)+ ...
    var_2st.BLP.main_problem.dual_lambda(f_end_Tau_out+1:f_start_Tau_act-1)'*details.f(f_end_Tau_out+1:f_start_Tau_act-1) + ...
    var_2st.BLP.main_problem.dual_lambda(f_end_Tau_act+1:end)'*details.f(f_end_Tau_act+1:end) ...
    ;

%%
for i = 1:length(set_respower)
    var_2st.BLP.main_problem.details.f(index_res(:,i),1) = ...
        -var_2st.BLP.main_problem.p_res(:,i);
end
for i = 1:length(set_loadpower)
    var_2st.BLP.main_problem.details.f(index_load(:,i),1) = ...
        -var_2st.BLP.main_problem.p_load(:,i);
end
var_2st.BLP.main_problem.details.f(index_Tau_out(:),1) = ...
    -var_2st.BLP.main_problem.Tau_out;
for i = 1:num_building
    var_2st.BLP.main_problem.details.f(index_Tau_act(:,i),1) = ...
        -var_2st.BLP.main_problem.Tau_act(:,i);
end

%% revised OA method
var_2st.BLP.main_problem.cost_binary = binvar(length(model.sub_problem.BLP.scenario),1,'full');
var_2st.BLP.main_problem.cost_max_min = sdpvar(length(model.sub_problem.BLP.scenario),1,'full');
for k = 1:length(model.sub_problem.BLP.scenario)
    model.sub_problem.BLP.main_problem.cons = ...
        model.sub_problem.BLP.main_problem.cons + ( ...
        0 <= var_2st.BLP.main_problem.cost_max_min(k) <= ...
        var_2st.BLP.main_problem.cost_bilinear(k).total_cost);
    model.sub_problem.BLP.main_problem.cons = ...
        model.sub_problem.BLP.main_problem.cons + ( ...
        0 <= var_2st.BLP.main_problem.cost_max_min(k) <= ...
        var_2st.BLP.main_problem.cost_binary(k) * 1e2*big_M);
end
model.sub_problem.BLP.main_problem.cons = ...
    model.sub_problem.BLP.main_problem.cons + ( ...
    sum(var_2st.BLP.main_problem.cost_binary) == 1);

%% cost
model.sub_problem.BLP.main_problem.obj = ...
    model.sub_problem.BLP.main_problem.obj + ...
    sum(var_2st.BLP.main_problem.cost_max_min);

%%
if DisplayTime
    t1 = clock;
    fprintf('%8.2f%s\n', etime(t1,t0), 's');
end
end