function cons_uncertainty = defineUncertaintyConstraints(var_u, var_2st)
%DEFINEUNCERTAINTYCONSTRAINTS Define uncertainty set constraints
%
%   This function defines budget uncertainty set constraints for the
%   uncertainty variables (deviations).
%
%   Inputs:
%       data - Data structure containing uncertainty parameters
%       var_u - Uncertainty variables structure
%
%   Outputs:
%       cons_uncertainty - YALMIP constraint object for uncertainty set
global data
cons_uncertainty = [];
[loc_profilestype] = deal(2);       % profiles
num_period = data.period;
num_building = size(data.buildings.param,1);
set_loadpower = find(data.profiles.bus(:,loc_profilestype) == 1);
set_respower = find(data.profiles.bus(:,loc_profilestype) == 2);
% details = model.sub_problem.details;

%% Unceratinty constraints
% uncertainty
% % p_res
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (0 <= var_u.p_res_pos <= 1) : '');
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (0 <= var_u.p_res_neg <= 1) : '');
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (sum(var_u.p_res_pos, 1) == ...
    sum(var_u.p_res_neg, 1)) : '');
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (sum(var_u.p_res_pos, 1) + ...
    sum(var_u.p_res_neg, 1) <= ...
    data.uncertainty.Gamma.p_res) : '');

% % p_load
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (0 <= var_u.p_load_pos <= 1) : '');
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (0 <= var_u.p_load_neg <= 1) : '');
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (sum(var_u.p_load_pos, 1) == ...
    sum(var_u.p_load_neg, 1)) : '');
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (sum(var_u.p_load_pos, 1) + ...
    sum(var_u.p_load_neg, 1) <= ...
    data.uncertainty.Gamma.p_load) : '');

% % Tau_out
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (0 <= var_u.Tau_out_pos <= 1) : '');
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (0 <= var_u.Tau_out_neg <= 1) : '');
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (sum(var_u.Tau_out_pos, 1) == ...
    sum(var_u.Tau_out_neg, 1)) : '');
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (sum(var_u.Tau_out_pos, 1) + ...
    sum(var_u.Tau_out_neg, 1) <= ...
    data.uncertainty.Gamma.Tau_out) : '');

% % Tau_act
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (0 <= var_u.Tau_act_pos <= 1) : '');
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (0 <= var_u.Tau_act_neg <= 1) : '');
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (sum(var_u.Tau_act_pos, 1) == ...
    sum(var_u.Tau_act_neg, 1)) : '');
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (sum(var_u.Tau_act_pos, 1) + ...
    sum(var_u.Tau_act_neg, 1) <= ...
    data.uncertainty.Gamma.Tau_act) : '');

% %
% % p_res
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (sum(var_u.p_res_pos + ...
    var_u.p_res_neg, 1) <= ...
    data.uncertainty.Gamma.p_res) : '');
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (sum(var_u.p_res_pos, 1) == ...
    sum(var_u.p_res_neg, 1)) : '');
% % p_load
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (sum(var_u.p_load_pos,1) == ...
    sum(var_u.p_load_neg, 1)) : '');
% % Tau_out
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (sum(var_u.Tau_out_pos,1) == ...
    sum(var_u.Tau_out_neg, 1)) : '');
% % Tau_act
cons_uncertainty = ...
    cons_uncertainty + ( ...
    (sum(var_u.Tau_act_pos,1) == ...
    sum(var_u.Tau_act_neg, 1)) : '');
% % 
% % % p_res
% cons_uncertainty = ...
%     cons_uncertainty + ( ...
%     (var_2st.res.p_fore(:,:) == ...
%     data.profiles.data(set_respower, :)' .* ...
%     ( 1 + ...
%     data.uncertainty.Deviation.p_res * ...
%     var_u.p_res_pos - ...
%     data.uncertainty.Deviation.p_res * ...
%     var_u.p_res_neg)) :   'p res');
% % % p_load
% cons_uncertainty = ...
%     cons_uncertainty + ( ...
%     (var_2st.bus.p_load(:,:) == ...
%     data.profiles.data(set_loadpower,:)' .* ( 1 + ...
%     data.uncertainty.Deviation.p_load * ...
%     var_u.p_load_pos - ...
%     data.uncertainty.Deviation.p_load * ...
%     var_u.p_load_neg)) : 'p load of bus');
% % % Tau_out
% cons_uncertainty = ...
%     cons_uncertainty + ( ...
%     (var_2st.building.Tau_out == ...
%     data.buildings.Tau_out .* ( 1 + ...
%     data.uncertainty.Deviation.Tau_out * ...
%     var_u.Tau_out_pos - ...
%     data.uncertainty.Deviation.Tau_out * ...
%     var_u.Tau_out_neg)) : 'Tau_out');
% % % Tau_act
% cons_uncertainty = ...
%     cons_uncertainty + ( ...
%     (var_2st.building.Tau_act == ...
%     data.buildings.Tau_act' .* ( 1 + ...
%     data.uncertainty.Deviation.Tau_act * ...
%     var_u.Tau_act_pos - ...
%     data.uncertainty.Deviation.Tau_act * ...
%     var_u.Tau_act_neg)) : 'Tau_act');
end