function cons_1st = defineFirstStageConstraints(var)
%DEFINEFIRSTSTAGECONSTRAINTS Define first-stage constraints
%
%   This function is refactored from examples/original_code/model_grid_1st.m,
%   model_heatingnetwork_1st.m, model_building_1st.m
%   with global variables removed.
%
%   NOTE: This is a simplified version. The original code contains very complex
%   constraint definitions spread across multiple files. Users should extract
%   constraints from the original code files and adapt them here.
%
%   Inputs:
%       data - Data structure
%       var - Variable structure containing base (first-stage) variables
%
%   Outputs:
%       cons_1st - YALMIP constraint object for first-stage constraints
global data
cons_1st = [];

% Extract parameters
[loc_devicebus, loc_devicetype, loc_pmax, loc_pmin, ...
    loc_es_cap, loc_es_pchr, loc_es_pdis, ...
    loc_es_etachr, loc_es_etadis, loc_es_loss, ...
    loc_es_capmax, loc_es_capmin, loc_es_capinitial, ...
    loc_gt_eta, loc_gt_loss, loc_gt_etahr, loc_eb_eta] = ...
    deal(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,14);   % device
[loc_tst_cap, loc_tst_hchr, loc_tst_hdis, loc_tst_etachr, loc_tst_etadis, ...
    loc_tst_loss, loc_tst_capmax, loc_tst_capmin, loc_tst_capinitial] = ...
    deal(loc_es_cap, loc_es_pchr, loc_es_pdis, ...
    loc_es_etachr, loc_es_etadis, loc_es_loss, ...
    loc_es_capmax, loc_es_capmin, loc_es_capinitial);
[loc_c2, loc_c1, loc_c0, loc_penalty, loc_om] = deal(5,6,7,8,9); % cost

%%
num_period = data.period;
% num_bus = size(data.grid.bus,1);
set_es = find(data.device.param(:,loc_devicetype) == 2);
set_tst = find(data.device.param(:,loc_devicetype) == 5);

%% ----------------------------Device--------------------------------------
    %% es
    if ~isempty(set_es)
        cons_1st = cons_1st + ( ...
            (var.es.p_chr_state + ...
            var.es.p_dis_state <= 1) : '');
        cons_1st = cons_1st + ( ...
            (0 <= var.es.p_chr <= ...
            var.es.p_chr_state .* ...
            (ones(num_period, 1)*data.device.param(set_es, loc_es_pchr)')) : ...
            'limit on p_chr of es');
        cons_1st = cons_1st + ( ...
            (0 <= var.es.p_dis <= ...
            var.es.p_dis_state(:,:).* ...
            (ones(num_period, 1)*data.device.param(set_es, loc_es_pdis)')) : ...
            'limit on p_dis of es');   
        cons_1st = cons_1st + ( ...
            (ones(num_period,1) * ...
            data.device.param(set_es, loc_es_capmin)'.* ...
            data.device.param(set_es, loc_es_cap)'<= ...
            var.es.soc(:,:) <= ...
            ones(num_period,1) * ...
            data.device.param(set_es, loc_es_capmax)'.* ...
            data.device.param(set_es, loc_es_cap)') : ...
            'limit on cap of es');
        cons_1st = cons_1st + ( ...
            (var.es.soc(end,:) == ...
            data.device.param(set_es, loc_es_capinitial)'.* ...
            data.device.param(set_es, loc_es_cap)') : ...
            'final soc of es');
        t = 1;
        cons_1st = cons_1st + ( ...
            (var.es.soc(t,:) == ...
            (1 - data.device.param(set_es, loc_es_loss)').* ...
            data.device.param(set_es, loc_es_capinitial)'.* ...
            data.device.param(set_es, loc_es_cap)'+ ...
            data.device.param(set_es, loc_es_etachr)'.* ...
            var.es.p_chr(t,:) - ...
            1./data.device.param(set_es, loc_es_etadis)'.* ...
            var.es.p_dis(t,:)) : ...
            'initial soc of es');

        t = 2:num_period;
        cons_1st = cons_1st + ( ...
            (var.es.soc(t,:) == ...
            ones(length(t),1)*(1 - data.device.param(set_es, loc_es_loss)').* ...
            var.es.soc(t-1,:) + ...
            ones(length(t),1)*data.device.param(set_es, loc_es_etachr)'.* ...
            var.es.p_chr(t,:) - ...
            ones(length(t),1)*1./data.device.param(set_es, loc_es_etadis)'.* ...
            var.es.p_dis(t,:)) : ....
            'soc equations of es');
    end

    %% tst
    if ~isempty(set_tst)
        cons_1st = cons_1st + ( ...
            (var.tst.h_chr_state + ...
            var.tst.h_dis_state <= 1) : '');

        cons_1st = cons_1st + ( ...
            (0 <= var.tst.h_chr <= ...
            var.tst.h_chr_state .* ...
            (ones(num_period, 1)*data.device.param(set_tst, loc_tst_hchr)')) : ...
            'limit on h_chr of tst');
        cons_1st = cons_1st + ( ...
            (0 <= var.tst.h_dis <= ...
            var.tst.h_dis_state(:,:).* ...
            (ones(num_period, 1)*data.device.param(set_tst, loc_tst_hdis)')) : ...
            'limit on h_dis of tst');   
        cons_1st = cons_1st + ( ...
            (ones(num_period,1) * ...
            data.device.param(set_tst, loc_tst_capmin)'.* ...
            data.device.param(set_tst, loc_tst_cap)'<= ...
            var.tst.soc(:,:) <= ...
            ones(num_period,1) * ...
            data.device.param(set_tst, loc_tst_capmax)'.* ...
            data.device.param(set_tst, loc_tst_cap)') : ...
            'limit on cap of tst');
        cons_1st = cons_1st + ( ...
            (var.tst.soc(end,:) == ...
            data.device.param(set_tst, loc_tst_capinitial)'.* ...
            data.device.param(set_tst, loc_tst_cap)') : ...
            'final soc of tst');
        t = 1;
        cons_1st = cons_1st + ( ...
            (var.tst.soc(t,:) == ...
            (1 - data.device.param(set_tst, loc_tst_loss)').* ...
            data.device.param(set_tst, loc_tst_capinitial)'.* ...
            data.device.param(set_tst, loc_tst_cap)'+ ...
            data.device.param(set_tst, loc_tst_etachr)'.* ...
            var.tst.h_chr(t,:) - ...
            1./data.device.param(set_tst, loc_tst_etadis)'.* ...
            var.tst.h_dis(t,:)) : ...
            'initial soc of es');

        t = 2:num_period;
        cons_1st = cons_1st + ( ...
            (var.tst.soc(t,:) == ...
            ones(length(t),1)*(1 - data.device.param(set_tst, loc_tst_loss)').* ...
            var.tst.soc(t-1,:) + ...
            ones(length(t),1)*data.device.param(set_tst, loc_tst_etachr)'.* ...
            var.tst.h_chr(t,:) - ...
            ones(length(t),1)*1./data.device.param(set_tst, loc_tst_etadis)'.* ...
            var.tst.h_dis(t,:)) : ....
            'soc equations of es');
    end

end


