function [system_data, training_data, test_data] = data_loader(params)
    %% 选择系统类型
    switch lower(params.system_kind)
        case 'ies'
            %% 电-热系统数据载入
            switch lower(params.system_scale)
                case 'small'
                    system_data = IES_6bus;
                case 'big'
                    system_data = IES_118bus;
                otherwise
                    error('无效的系统规模选择。可用选项: small，big');
            end
            system_capacity = sum(system_data.plimit.upper) + sum(system_data.resplimit.upper) + sum(system_data.chpplimit.p4);
        case 'eps'
            %% 电力系统数据载入
            switch lower(params.system_scale)
                case 'small'
                    system_data = case9_modified;
                case 'big'
                    system_data = case118_modified;
                otherwise
                    error('无效的系统规模选择。可用选项: small，big');
            end
            system_capacity = sum(system_data.plimit.upper) + sum(system_data.resplimit.upper);
        case 'ies_simplified'
            system_data = simplified_IES_118bus;
            system_capacity = sum(system_data.plimit.upper) + sum(system_data.resplimit.upper) + sum(system_data.chpplimit.p4);

        otherwise
            error('无效的系统类型选择。可用选项：ies，eps，ies_simplified');
    end
    
    %% 训练集载入
    [training_data.totalload_feature_data,...
     training_data.totalload_realization_data,...
     ~,...
     ~,...
     ~,...
     ~,...
     training_data.RES_feature_data,...  % wallonias_wind_feature_data
     ~,...
     ~,...
     training_data.RES_realization_data,...  % wallonias_wind_realization_data
     ~,...
     ~,...
     ~,...
     ~,...
     training_data.temperature_data] = Belgium_load_RES_dataload('2023-01-01 00:00:00',...
                                                                '2023-12-31 23:45:00',...
                                                                params.train_start_time,...
                                                                params.train_end_time,...
                                                                1,...
                                                                '2023Belguim_load_data.xlsx',...
                                                                '2023Belguim_wind_data.xlsx',...
                                                                '2023Belguim_solar_data.xlsx',...
                                                                '2023Belguim_temperature_data.xlsx');
    
    %% 训练集：归一化-实际值  
    training_data.totalload_feature_data = training_data.totalload_feature_data * (0.15 * system_capacity) + 0.45 * system_capacity;   % 负荷控制在0.25-0.5倍系统容量之间
    training_data.totalload_realization_data = training_data.totalload_realization_data * (0.15* system_capacity) + 0.45 * system_capacity;   % 负荷控制在0.25-0.5倍系统容量之间
    training_data.RES_feature_data = training_data.RES_feature_data * (2 * sum(system_data.resplimit.upper)) + 0.05 * sum(system_data.resplimit.upper);
    training_data.RES_realization_data = training_data.RES_realization_data * (2 * sum(system_data.resplimit.upper)) + 0.05 * sum(system_data.resplimit.upper);
    training_data.RES_realization_data = training_data.RES_realization_data * system_data.RES_weight';

    % 计算训练集时间数
    training_data.Ntime = size(training_data.totalload_realization_data,1);
    if strcmp(params.system_kind, 'ies')
        training_data.Ntime_heat = size(training_data.totalload_realization_data, 1) * (1 / system_data.heat_interval);
    end
    assert(mod(training_data.Ntime,24)==0, '时间维度必须是24的整数倍');
    training_data.num_blocks = training_data.Ntime / 24; % 分块

    % 计算每个负荷的负荷数据
    training_data.pload_realization_data = training_data.totalload_realization_data * system_data.load_weight';
    training_data.pres_realization_data = training_data.RES_realization_data;

    %% 测试集载入
    [test_data.totalload_feature_data,...
     test_data.totalload_realization_data,...
     ~,...
     ~,...
     ~,...
     ~,...
     test_data.RES_feature_data,...  % wallonias_wind_feature_data
     ~,...
     ~,...
     test_data.RES_realization_data,...  % wallonias_wind_realization_data
     ~,...
     ~,...
     ~,...
     ~,...
     test_data.temperature_data] = Belgium_load_RES_dataload('2023-01-01 00:00:00',...
                                                            '2023-12-31 23:45:00',...
                                                            params.test_start_time,...
                                                            params.test_end_time,...
                                                            1,...
                                                            '2023Belguim_load_data.xlsx',...
                                                            '2023Belguim_wind_data.xlsx',...
                                                            '2023Belguim_solar_data.xlsx',...
                                                            '2023Belguim_temperature_data.xlsx');
    
    %% 测试集：归一化-实际值
    test_data.totalload_feature_data = test_data.totalload_feature_data * (0.15 * system_capacity) + 0.45 * system_capacity;   % 负荷控制在0.25-0.5倍系统容量之间
    test_data.totalload_realization_data = test_data.totalload_realization_data * (0.15 * system_capacity) + 0.45 * system_capacity;   % 负荷控制在0.25-0.5倍系统容量之间
    test_data.RES_feature_data = test_data.RES_feature_data * (2 * sum(system_data.resplimit.upper)) + 0.05 * sum(system_data.resplimit.upper);
    test_data.RES_realization_data = test_data.RES_realization_data * (2 * sum(system_data.resplimit.upper)) + 0.05 * sum(system_data.resplimit.upper);
    test_data.RES_realization_data = test_data.RES_realization_data * system_data.RES_weight';
    % 计算测试集时间数
    test_data.Ntime = size(test_data.totalload_realization_data,1);
    if strcmp(params.system_kind, 'ies')
        test_data.Ntime_heat = size(test_data.totalload_realization_data, 1) * (1 / system_data.heat_interval);
    end

    % 计算每个负荷的负荷数据
    test_data.pload_realization_data = test_data.totalload_realization_data * system_data.load_weight';
    test_data.pres_realization_data = test_data.RES_realization_data;
end
