function model = model_building(system_data, training_data, params)
    % 定义预测模型参数
    model.var.theta = sdpvar(size(training_data.RES_feature_data,2)+1,1,'full');
    % 预测值
    pres_forecast = model.var.theta(1) + ...
        training_data.RES_feature_data * model.var.theta(2:end);
    pres_forecast = pres_forecast * system_data.RES_weight';

    %% 选择系统类型
    switch lower(params.system_kind)
        case 'eps'    
        [model.var_lower, model.constraints_lower, model.objective_UC1] = ...
            EPS_UC_model_stage1(params, system_data, training_data, pres_forecast);
        [model.var_upper, model.constraints_upper, model.objective_UC2] = ...
            EPS_UC_model_stage2(params, system_data, training_data, model.var_lower);

%         solution = optimize(model.constraints_lower + model.constraints_upper, model.objective_UC2, sdpsettings('solver','gurobi','verbose',1));
%         Solution = myFun_GetValue(model);
        %% 变量分组
        model.var_xu = [reshape(model.var_upper.pgen_up, [], 1); ...
                        reshape(model.var_upper.pgen_down, [], 1); ...
                        reshape(model.var_upper.ru_2stage, [], 1); ...
                        reshape(model.var_upper.rd_2stage, [], 1); ...
                        reshape(model.var_upper.rescurtailment_2stage, [], 1); ...
                        reshape(model.var_upper.loadshedding_2stage, [], 1); ...
                        reshape(model.var.theta, [], 1)];
        model.var_zu = [];
        model.var_xl = [reshape(model.var_lower.pgen, [], 1); ...
                        reshape(model.var_lower.ru, [], 1); ...
                        reshape(model.var_lower.rd, [], 1); ...
                        reshape(model.var_lower.rescurtailment, [], 1); ...
                        reshape(model.var_lower.loadshedding, [], 1)];
        model.var_zl = [reshape(model.var_lower.u, [], 1); ...
                        reshape(model.var_lower.v, [], 1); ...
                        reshape(model.var_lower.w, [], 1)];
        model.var.var_lower = model.var_lower;
        model.var.var_upper = model.var_upper;

        case 'ies'    
        [model.var_lower, model.constraints_lower, model.objective_UC1] = ...
            IES_modeling_firststage(params, system_data, training_data, pres_forecast);
        [model.var_upper, model.constraints_upper, model.objective_UC2] = ...
            IES_modeling_secondstage(params, system_data, training_data, model.var_lower);

%         solution = optimize(model.constraints_lower + model.constraints_upper, model.objective_UC2, sdpsettings('solver','gurobi','verbose',1));
%         Solution = myFun_GetValue(model);
        %% 变量分组
        model.var_xu = [reshape(model.var_upper.pgen_up, [], 1); ...
                        reshape(model.var_upper.pgen_down, [], 1); ...
                        reshape(model.var_upper.ru_2stage, [], 1); ...
                        reshape(model.var_upper.rd_2stage, [], 1); ...
                        reshape(model.var_upper.rescurtailment_2stage, [], 1); ...
                        reshape(model.var_upper.loadshedding_2stage, [], 1); ...
                        reshape(model.var.theta, [], 1); ...
                        reshape(model.var_upper.pchp_up, [], 1); ...
                        reshape(model.var_upper.pchp_down, [], 1); ...
                        reshape(model.var_upper.hchp_up, [], 1); ...
                        reshape(model.var_upper.hchp_down, [], 1); ...
                        reshape(model.var_upper.xichp_2stage, [], 1); ...
                        reshape(model.var_upper.Tau_s_out_2stage, [], 1); ...
                        reshape(model.var_upper.Tau_s_in_2stage, [], 1); ...
                        reshape(model.var_upper.Tau_r_out_2stage, [], 1); ...
                        reshape(model.var_upper.Tau_r_in_2stage, [], 1); ...
                        reshape(model.var_upper.Tau_s_n_2stage, [], 1); ...
                        reshape(model.var_upper.Tau_r_n_2stage, [], 1); ...
                        reshape(model.var_upper.hhchp_2stage, [], 1); ...
                        reshape(model.var_upper.hload_2stage, [], 1); ...
                        reshape(model.var_upper.Tau_building_2stage, [], 1)];

        model.var_zu = [];
        model.var_xl = [reshape(model.var_lower.pgen, [], 1); ...
                        reshape(model.var_lower.ru, [], 1); ...
                        reshape(model.var_lower.rd, [], 1); ...
                        reshape(model.var_lower.rescurtailment, [], 1); ...
                        reshape(model.var_lower.loadshedding, [], 1); ...
                        reshape(model.var_lower.pchp, [], 1); ...
                        reshape(model.var_lower.hchp, [], 1); ...
                        reshape(model.var_lower.xichp, [], 1); ...
                        reshape(model.var_lower.Tau_s_out, [], 1); ...
                        reshape(model.var_lower.Tau_s_in, [], 1); ...
                        reshape(model.var_lower.Tau_r_out, [], 1); ...
                        reshape(model.var_lower.Tau_r_in, [], 1); ...
                        reshape(model.var_lower.Tau_s_n, [], 1); ...
                        reshape(model.var_lower.Tau_r_n, [], 1); ...
                        reshape(model.var_lower.hhchp, [], 1); ...
                        reshape(model.var_lower.hload, [], 1); ...
                        reshape(model.var_lower.Tau_building, [], 1)];

        model.var_zl = [reshape(model.var_lower.u, [], 1); ...
                        reshape(model.var_lower.v, [], 1); ...
                        reshape(model.var_lower.w, [], 1)];
        model.var.var_lower = model.var_lower;
        model.var.var_upper = model.var_upper;
        case 'ies_simplified'
        [model.var_lower, model.constraints_lower, model.objective_UC1] = ...
            simplified_IES_modeling_firststage(params, system_data, training_data, pres_forecast);
        [model.var_upper, model.constraints_upper, model.objective_UC2] = ...
            simplified_IES_modeling_secondstage(params, system_data, training_data, model.var_lower);

        %% 变量分组
        model.var_xu = [reshape(model.var_upper.pgen_up, [], 1); ...
                        reshape(model.var_upper.pgen_down, [], 1); ...
                        reshape(model.var_upper.ru_2stage, [], 1); ...
                        reshape(model.var_upper.rd_2stage, [], 1); ...
                        reshape(model.var_upper.rescurtailment_2stage, [], 1); ...
                        reshape(model.var_upper.loadshedding_2stage, [], 1); ...
                        reshape(model.var.theta, [], 1); ...
                        reshape(model.var_upper.pchp_up, [], 1); ...
                        reshape(model.var_upper.pchp_down, [], 1); ...
                        reshape(model.var_upper.hchp_up, [], 1); ...
                        reshape(model.var_upper.hchp_down, [], 1); ...
                        reshape(model.var_upper.xichp_2stage, [], 1)];

        model.var_zu = [];
        model.var_xl = [reshape(model.var_lower.pgen, [], 1); ...
                        reshape(model.var_lower.ru, [], 1); ...
                        reshape(model.var_lower.rd, [], 1); ...
                        reshape(model.var_lower.rescurtailment, [], 1); ...
                        reshape(model.var_lower.loadshedding, [], 1); ...
                        reshape(model.var_lower.pchp, [], 1); ...
                        reshape(model.var_lower.hchp, [], 1); ...
                        reshape(model.var_lower.xichp, [], 1)];

        model.var_zl = [reshape(model.var_lower.u, [], 1); ...
                        reshape(model.var_lower.v, [], 1); ...
                        reshape(model.var_lower.w, [], 1)];
        model.var.var_lower = model.var_lower;
        model.var.var_upper = model.var_upper;

    end
%     model.constraints_upper = model.constraints_upper + ...
%         (model.var.theta(2:5, 1) >= 0);
%     model.constraints_upper = model.constraints_upper + ...
%         (model.var.theta(2:5, 1) <= 1);
%     model.constraints_upper = model.constraints_upper + ...
%         (pres_forecast >= 0);

    %% 目标函数处理
    % 目标函数（L1正则化要线性化）
    switch params.regularization_selection
        case 0 % 不正则化
            model.objective_upper = model.objective_UC2;
        case 1 % L1正则化
            % 定义线性化辅助变量
            model.var.piecewise_aux = sdpvar(size(model.var.theta,1), ...
                                             size(model.var.theta,2),'full');
            % 加入上层变量
            model.var_xu = [model.var_xu; ...
                            reshape(model.var.piecewise_aux,[],1)];
            % 辅助约束
            model.constraints_upper = model.constraints_upper + ...
                (model.var.piecewise_aux >= model.var.theta);
            model.constraints_upper = model.constraints_upper + ...
                (model.var.piecewise_aux >= -model.var.theta);
            % 定义上层目标函数
            model.objective_upper = model.objective_UC2 + ...
                                    params.regularization_coefficient * ...
                                    sum(model.var.piecewise_aux,'all');
        case 2  % 
            model.objective_upper = model.objective_UC2 + ...
                                    params.regularization_coefficient * ...
                                    sum((model.var.theta)'*(model.var.theta));
        otherwise
            error('Check whether params.regularization_selection is correct');
    end
    model.objective_lower = model.objective_UC1;
end
